-- Dynamic table that calculates OCOGS carveouts with aggregated receiver revenue
-- Co-authored with CoCo
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

-- Dynamic table that calculates OCOGS carveouts
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_OCOGS_CARVEOUTS
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    c.BILLINGS_MONTH,
    c.OCOGS_COMPONENT,
    CASE
        WHEN c.FLAT_RATE IS NOT NULL THEN
            c.FLAT_RATE
        WHEN c.CARVEOUTS_PERCENTAGE IS NOT NULL THEN
            r.TOTAL_REVENUE * c.CARVEOUTS_PERCENTAGE / 100
    END AS OCOGS_CARVEOUTS
FROM FIELD_SYSTEMS_EDW.GENERAL.OCOGS_CARVEOUTS_CONFIGURATION c
LEFT JOIN (
    SELECT BILLINGS_MONTH, SUM(RECEIVER_REVENUE) AS TOTAL_REVENUE
    FROM FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_BOTTOMS_UP_REVENUE_FORECAST
    GROUP BY BILLINGS_MONTH
) r
    ON c.BILLINGS_MONTH = r.BILLINGS_MONTH;