USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    d.BILLING_MONTH,
    d."Grouping",
    d.MAXIMUM_DIRECT_COST * SUM(b."Quantity Invoiced") AS DCOGS_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS_MARGIN d
INNER JOIN FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_BILLINGS_PRICE_LIST_WITH_GROUPINGS_MODEL b
    ON b."Fiscal Month" = d.BILLING_MONTH
    AND b."Grouping" = d."Grouping"
GROUP BY d.BILLING_MONTH, d."Grouping", d.MAXIMUM_DIRECT_COST
ORDER BY d.BILLING_MONTH ASC, d."Grouping" ASC;