USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA DISPLAY_AGIS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.DISPLAY_AGIS.VIEW_AG_DCOGS_CONSOLIDATED AS

WITH current_period AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),

actuals AS (
    SELECT
        UPPER("Grouping") AS RECEIVER_CODE,
        BILLING_MONTH,
        SUM(DCOGS_AMOUNT) AS EXPENDITURE_AMOUNT,
        'ACTUAL' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS
    CROSS JOIN current_period cp
    WHERE BILLING_MONTH < cp.FISCAL_MONTH_CODE
    GROUP BY UPPER("Grouping"), BILLING_MONTH
),

forecast AS (
    SELECT
        UPPER(RECEIVER_CODE) AS RECEIVER_CODE,
        BILLING_MONTH,
        SUM(EXPENDITURE_AMOUNT) AS EXPENDITURE_AMOUNT,
        'FORECAST' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_DCOGS_FORECAST
    CROSS JOIN current_period cp
    WHERE BILLING_MONTH >= cp.FISCAL_MONTH_CODE
    GROUP BY UPPER(RECEIVER_CODE), BILLING_MONTH
),

combined AS (
    SELECT RECEIVER_CODE, BILLING_MONTH, EXPENDITURE_AMOUNT, SOURCE
    FROM actuals

    UNION ALL

    SELECT RECEIVER_CODE, BILLING_MONTH, EXPENDITURE_AMOUNT, SOURCE
    FROM forecast
)

SELECT c.RECEIVER_CODE, c.BILLING_MONTH, c.EXPENDITURE_AMOUNT, c.SOURCE
FROM combined c
LEFT JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVERS_LIST r
    ON UPPER(c.RECEIVER_CODE) = UPPER(r.RECEIVER_CODE)
ORDER BY r.SORT_ORDER, c.BILLING_MONTH;
