USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_OPERATING_REVENUE_FORECAST
(
    BILLING_MONTH,
    TOTAL_OPERATING_REVENUE
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    r.BILLING_MONTH,
    r.TOTAL_REVENUE - c.TOTAL_AMOUNT AS TOTAL_REVENUE
FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_FORECAST r
JOIN FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_COGS_OPEX_FORECAST c
    ON r.BILLING_MONTH = c.BILLING_MONTH
ORDER BY r.BILLING_MONTH;
