USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_FORECAST(
	BILLING_MONTH,
	TOTAL_REVENUE,
	OTHER_BA,
	NATURAL_ACCOUNT
) target_lag = '1 minute' refresh_mode = FULL initialize = ON_CREATE warehouse = FIELD_SYSTEMS_GENERAL_WAREHOUSE
 as
SELECT
    BILLING_MONTH,
    BILLINGS_TOTAL - (PCS_CARVEOUT + RTX_CARVEOUT) + (PCS_AMORTIZED_FROM_PAST + RTX_AMORTIZED_FROM_PAST) AS TOTAL_REVENUE,
    OTHER_BA,
    NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_COMPONENTS
ORDER BY BILLING_MONTH;