USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

create or replace dynamic table FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_COMPONENTS(
	BILLING_MONTH,
	BILLINGS_TOTAL,
	PCS_CARVEOUT,
	RTX_CARVEOUT,
	PCS_AMORTIZED_IN,
	RTX_AMORTIZED_IN,
	OTHER_BA,
	NATURAL_ACCOUNT
) target_lag = '1 minute' refresh_mode = FULL initialize = ON_CREATE warehouse = FIELD_SYSTEMS_GENERAL_WAREHOUSE
 as
WITH billing_months AS (
    SELECT DISTINCT
        FISCAL_YEAR || '-' || LPAD(FISCAL_MONTH::VARCHAR, 2, '0') AS BILLING_MONTH,
        FISCAL_MONTH_START
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE FISCAL_YEAR = YEAR(CURRENT_DATE())
),

-- A: Total Billings per month
a_billings AS (
    SELECT
        BILLING_MONTH,
        SUM(BILLING_TOTAL) AS BILLINGS_TOTAL
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST
    GROUP BY BILLING_MONTH
),

-- B1: PCS Carveout per month
b1_pcs_carveout AS (
    SELECT
        BILLING_MONTH,
        SUM(CARVEOUT_AMOUNT) AS PCS_CARVEOUT,
        MAX(OTHER_BA) AS OTHER_BA,
        MAX(NATURAL_ACCOUNT) AS NATURAL_ACCOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_PCS_CARVEOUT_FORECAST
    GROUP BY BILLING_MONTH
),

-- B2: RTX Carveout per month
b2_rtx_carveout AS (
    SELECT
        BILLING_MONTH,
        SUM(CARVEOUT_AMOUNT) AS RTX_CARVEOUT,
        MAX(OTHER_BA) AS OTHER_BA,
        MAX(NATURAL_ACCOUNT) AS NATURAL_ACCOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_CARVEOUT_FORECAST
    GROUP BY BILLING_MONTH
),

-- Map TARGET_MONTH to BILLING_MONTH via fiscal calendar
target_month_map AS (
    SELECT DISTINCT
        FISCAL_MONTH_START,
        FISCAL_YEAR || '-' || LPAD(FISCAL_MONTH::VARCHAR, 2, '0') AS TARGET_BILLING_MONTH
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
),

-- Current fiscal month
current_fiscal AS (
    SELECT DISTINCT
        FISCAL_YEAR || '-' || LPAD(FISCAL_MONTH::VARCHAR, 2, '0') AS CURRENT_BILLING_MONTH
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),

-- C1 Forecast: PCS Amortized amounts landing in each target month (future months)
c1_pcs_forecast AS (
    SELECT
        tm.TARGET_BILLING_MONTH AS BILLING_MONTH,
        SUM(paf.CARVEOUT_AMOUNT_AMORTIZED) AS PCS_AMORTIZED_IN
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_PCS_AMORTIZED_FORECAST paf
    JOIN target_month_map tm
        ON TRY_TO_DATE(REPLACE(paf.TARGET_MONTH, '"', '')) = tm.FISCAL_MONTH_START
    WHERE tm.TARGET_BILLING_MONTH > (SELECT CURRENT_BILLING_MONTH FROM current_fiscal)
    GROUP BY tm.TARGET_BILLING_MONTH
),

-- C1 Actuals: PCS Waterfall for past/current months (unpivoted)
c1_pcs_actuals AS (
    SELECT '2026-01' AS BILLING_MONTH, SUM("2026-M01") AS PCS_AMORTIZED_IN FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-02', SUM("2026-M02") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-03', SUM("2026-M03") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-04', SUM("2026-M04") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-05', SUM("2026-M05") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-06', SUM("2026-M06") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-07', SUM("2026-M07") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-08', SUM("2026-M08") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-09', SUM("2026-M09") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-10', SUM("2026-M10") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-11', SUM("2026-M11") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-12', SUM("2026-M12") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL GROUP BY 1
),

-- C1 Combined: actuals for past/current, forecast for future
c1_combined AS (
    SELECT BILLING_MONTH, PCS_AMORTIZED_IN
    FROM c1_pcs_actuals
    WHERE BILLING_MONTH <= (SELECT CURRENT_BILLING_MONTH FROM current_fiscal)
    UNION ALL
    SELECT BILLING_MONTH, PCS_AMORTIZED_IN
    FROM c1_pcs_forecast
),

-- C2 Forecast: RTX Amortized amounts landing in each target month (future months)
c2_rtx_forecast AS (
    SELECT
        tm.TARGET_BILLING_MONTH AS BILLING_MONTH,
        SUM(raf.CARVEOUT_AMOUNT_AMORTIZED) AS RTX_AMORTIZED_IN
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_AMORTIZED_FORECAST raf
    JOIN target_month_map tm
        ON TRY_TO_DATE(REPLACE(raf.TARGET_MONTH, '"', '')) = tm.FISCAL_MONTH_START
    WHERE tm.TARGET_BILLING_MONTH > (SELECT CURRENT_BILLING_MONTH FROM current_fiscal)
    GROUP BY tm.TARGET_BILLING_MONTH
),

-- C2 Actuals: RTX Waterfall for past/current months (unpivoted)
c2_rtx_actuals AS (
    SELECT '2026-01' AS BILLING_MONTH, SUM("2026-M01") AS RTX_AMORTIZED_IN FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-02', SUM("2026-M02") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-03', SUM("2026-M03") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-04', SUM("2026-M04") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-05', SUM("2026-M05") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-06', SUM("2026-M06") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-07', SUM("2026-M07") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-08', SUM("2026-M08") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-09', SUM("2026-M09") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-10', SUM("2026-M10") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-11', SUM("2026-M11") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
    UNION ALL
    SELECT '2026-12', SUM("2026-M12") FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL GROUP BY 1
),

-- C2 Combined: actuals for past/current, forecast for future
c2_combined AS (
    SELECT BILLING_MONTH, RTX_AMORTIZED_IN
    FROM c2_rtx_actuals
    WHERE BILLING_MONTH <= (SELECT CURRENT_BILLING_MONTH FROM current_fiscal)
    UNION ALL
    SELECT BILLING_MONTH, RTX_AMORTIZED_IN
    FROM c2_rtx_forecast
)

SELECT
    bm.BILLING_MONTH,
    COALESCE(a.BILLINGS_TOTAL, 0) AS BILLINGS_TOTAL,
    COALESCE(b1.PCS_CARVEOUT, 0) AS PCS_CARVEOUT,
    COALESCE(b2.RTX_CARVEOUT, 0) AS RTX_CARVEOUT,
    COALESCE(c1.PCS_AMORTIZED_IN, 0) AS PCS_AMORTIZED_IN,
    COALESCE(c2.RTX_AMORTIZED_IN, 0) AS RTX_AMORTIZED_IN,
    COALESCE(b1.OTHER_BA, b2.OTHER_BA) AS OTHER_BA,
    COALESCE(b1.NATURAL_ACCOUNT, b2.NATURAL_ACCOUNT) AS NATURAL_ACCOUNT
FROM billing_months bm
LEFT JOIN a_billings a ON bm.BILLING_MONTH = a.BILLING_MONTH
LEFT JOIN b1_pcs_carveout b1 ON bm.BILLING_MONTH = b1.BILLING_MONTH
LEFT JOIN b2_rtx_carveout b2 ON bm.BILLING_MONTH = b2.BILLING_MONTH
LEFT JOIN c1_combined c1 ON bm.BILLING_MONTH = c1.BILLING_MONTH
LEFT JOIN c2_combined c2 ON bm.BILLING_MONTH = c2.BILLING_MONTH
ORDER BY bm.BILLING_MONTH;