USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

create or replace dynamic table FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_FORECAST(
	BILLING_MONTH,
	REVENUE,
	OTHER_BA,
	NATURAL_ACCOUNT
) target_lag = '1 minute' refresh_mode = FULL initialize = ON_CREATE warehouse = FIELD_SYSTEMS_GENERAL_WAREHOUSE
 as
SELECT
    BILLING_MONTH,
    BILLINGS_TOTAL - (PCS_CARVEOUT + RTX_CARVEOUT) + (PCS_AMORTIZED_IN + RTX_AMORTIZED_IN) AS REVENUE,
    OTHER_BA,
    NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_COMPONENTS
ORDER BY BILLING_MONTH;