USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA DISPLAY_AGIS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.DISPLAY_AGIS.VIEW_AG_TOTAL_REVENUE_CONSOLIDATED AS

WITH current_period AS (
    SELECT DISTINCT
        FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),

actuals AS (
    SELECT
        "Fiscal Month" AS BILLING_MONTH,
        REVENUE,
        'ACTUAL' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_REVENUE_ACTUALS
    CROSS JOIN current_period cp
    WHERE "Fiscal Month" < cp.FISCAL_MONTH_CODE
),

forecast AS (
    SELECT
        LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) AS BILLING_MONTH,
        TOTAL_REVENUE AS REVENUE,
        'FORECAST' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_FORECAST
    CROSS JOIN current_period cp
    WHERE LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) >= cp.FISCAL_MONTH_CODE
)

SELECT BILLING_MONTH, REVENUE, SOURCE
FROM actuals

UNION ALL

SELECT BILLING_MONTH, REVENUE, SOURCE
FROM forecast

ORDER BY BILLING_MONTH;


select * from FIELD_SYSTEMS_EDW.DISPLAY_AGIS.VIEW_AG_TOTAL_REVENUE_CONSOLIDATED;