-- Ag Bottoms Up Revenue Forecast --


-- Setup --
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENTS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Create dynamic table for Bottoms Up Revenue Calculation
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENTS.DYNAMIC_AG_BOTTOMS_UP_BILLIINGS_FORECAST
    TARGET_LAG = '1 minute'
    WAREHOUSE = 'FIELD_SYSTEMS_GENERAL_WAREHOUSE'
    AS
    SELECT DYNAMIC_AG_UNIT_PRICE_TABLE.RECEIVER_CODE
           , SUM("Unit Selling Price USD" * "UNITS_SOLD") AS RECEIVER_REVENUE
           , DYNAMIC_AG_UNIT_SALES_TABLE.BILLINGS_MONTH
    FROM DYNAMIC_AG_UNIT_PRICE_TABLE
    JOIN DYNAMIC_AG_UNIT_SALES_TABLE
    ON DYNAMIC_AG_UNIT_PRICE_TABLE.RECEIVER_CODE = DYNAMIC_AG_UNIT_SALES_TABLE.RECEIVER_CODE
    GROUP BY DYNAMIC_AG_UNIT_PRICE_TABLE.RECEIVER_CODE
             , DYNAMIC_AG_UNIT_SALES_TABLE.BILLINGS_MONTH;


-- SELECT * from FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENTS.DYNAMIC_AG_BOTTOMS_UP_BILLIINGS_FORECAST;
