USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENTS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;



CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENTS.AG_BILLINGS_ACTUALS AS

SELECT "GL Date Period ID" AS BILLINGS_MONTH,
       "Grouping" AS RECEIVER_CODE,
       SUM("Extended Amount USD") AS ACTUAL_REVENUE
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_BILLINGS_PRICE_LIST_WITH_GROUPINGS_MODEL
GROUP BY "GL Date Period ID", "Grouping"
ORDER BY "Invoice Date Period ID" asc, "Grouping" asc;


-- SELECT * FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENTS.AG_BILLINGS_ACTUALS;