USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;



CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_BOTTOMS_UP_BILLINGS_CONSOLIDATED AS

WITH current_period AS (
    SELECT DISTINCT
        LEFT(FISCAL_MONTH_CODE, 4) || '-' || RIGHT(FISCAL_MONTH_CODE, 2) AS FISCAL_MONTH
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),

actuals AS (
    SELECT
        LEFT(BILLINGS_MONTH, 4) || '-' || RIGHT(BILLINGS_MONTH, 2) AS BILLINGS_MONTH,
        RECEIVER_CODE,
        ACTUAL_REVENUE AS REVENUE,
        'ACTUAL' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_BILLINGS_ACTUALS
    CROSS JOIN current_period cp
    WHERE LEFT(BILLINGS_MONTH, 4) || '-' || RIGHT(BILLINGS_MONTH, 2) < cp.FISCAL_MONTH
),

forecast AS (
    SELECT
        BILLINGS_MONTH,
        RECEIVER_CODE,
        RECEIVER_REVENUE AS REVENUE,
        'FORECAST' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLIINGS_FORECAST
    CROSS JOIN current_period cp
    WHERE BILLINGS_MONTH >= cp.FISCAL_MONTH
)

SELECT BILLINGS_MONTH, RECEIVER_CODE, REVENUE, SOURCE
FROM actuals

UNION ALL

SELECT BILLINGS_MONTH, RECEIVER_CODE, REVENUE, SOURCE
FROM forecast

ORDER BY BILLINGS_MONTH, RECEIVER_CODE;
