-- Ag Unit Sales --


-- Setup --
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;



CREATE OR REPLACE TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_UNIT_PRICE_TABLE
    TARGET_LAG = '1 minute'
    WAREHOUSE = 'FIELD_SYSTEMS_GENERAL_WAREHOUSE'
    AS
    -- Get this from SIGMA_WRITEBACK table

-- SELECT * FROM SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_UNIT_PRICE_TABLE;
