-- Dynamic tables: CONFIGURATION_AG_DCOGS (Sigma writeback) and DYNAMIC_AG_DCOGS_FORECAST
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_DCOGS
(
    RECEIVER_CODE,
    BILLING_MONTH,
    EXPENDITURE_PERCENTAGE,
    RATE_PER_UNIT,
    NATURAL_ACCOUNT,
    OTHER_BA
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    "TAHUGC2T42" AS RECEIVER_CODE,
    SPLIT_PART("MQZYGU9BJV", '-', 1) || '-' || LPAD(SPLIT_PART("MQZYGU9BJV", '-', 2), 2, '0') AS BILLING_MONTH,
    "NSXXGOQFKO" AS PERCENTAGE,
    "ZE8ANG6KCM" AS RATE_PER_UNIT,
    "ZNROAYNDL_" AS NATURAL_ACCOUNT,
    "YWXNINPI9O" AS OTHER_BA
FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_fa75c59d_158b_4f20_87e9_302285dae778"
WHERE "TAHUGC2T42" IS NOT NULL
  AND TOMBSTONE_VERSION IS NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY "TAHUGC2T42", "MQZYGU9BJV"
    ORDER BY UPDATED_AT DESC
) = 1;