-- Use fiscal calendar to standardize fiscal period and calculate carveout
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_DCOGS_ACTUALS_MARGIN
    TARGET_LAG = '1 minute'
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    b."Fiscal Month" AS BILLING_MONTH,
    b."Grouping",
    MAX(c."Item Cost") AS MAXIMUM_DIRECT_COST
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_BILLINGS_PRICE_LIST_WITH_GROUPINGS_MODEL b
LEFT JOIN FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_FROZEN_COST_ARF c
    ON b."item" = c."Item"
INNER JOIN FIELD_SYSTEMS_EDW.GENERAL.DIMENSION_AGIS_RECEIVERS r
    ON UPPER(b."Grouping") = UPPER(r.RECEIVER_CODE)
GROUP BY b."Fiscal Month", b."Grouping"
ORDER BY b."Fiscal Month", b."Grouping";