USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_DCOGS_FORECAST
(
    RECEIVER_CODE,
    BILLING_MONTH,
    EXPENDITURE_AMOUNT,
    OTHER_BA,
    NATURAL_ACCOUNT
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    c.RECEIVER_CODE,
    c.BILLING_MONTH,
    CASE
        WHEN c.EXPENDITURE_PERCENTAGE IS NOT NULL
            THEN (c.EXPENDITURE_PERCENTAGE / 100) * r.BILLING_TOTAL
        WHEN c.RATE_PER_UNIT IS NOT NULL
            THEN c.RATE_PER_UNIT * u.UNITS_SOLD
    END AS EXPENDITURE_AMOUNT,
    c.OTHER_BA,
    c.NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_DCOGS c
LEFT JOIN FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST r
    ON c.RECEIVER_CODE = r.RECEIVER_CODE
    AND c.BILLING_MONTH = r.BILLING_MONTH
LEFT JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVER_UNIT_SALES u
    ON c.RECEIVER_CODE = u.RECEIVER_CODE
    AND c.BILLING_MONTH = u.BILLING_MONTH;