USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.PCS_CARVEOUT_ACTUALS AS

SELECT
    "Invoice Date Period ID" AS BILLINGS_MONTH,
    "Grouping" AS RECEIVER_CODE,
    SUM("TAP Extended") AS ACTUAL_REVENUE
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_BILLINGS_TAP
GROUP BY "Invoice Date Period ID", "Grouping"
ORDER BY "Invoice Date Period ID" asc, "Grouping" asc;


SELECT * FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.PCS_CARVEOUT_ACTUALS;