-- Use fiscal calendar to standardize fiscal period and calculate carveout
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;



CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_PCS_WATERFALL AS
SELECT *
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.PCS_Carveout;


-- SELECT * FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_PCS_WATERFALL;