USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;
---------------------------------------------------------------------
-- 4. PCS_AMORTIZED_DETAIL (Intermediate Table)
-- Materializes the UDTF output first (Snowflake cannot aggregate
-- directly over lateral SQL UDTF columns).
---------------------------------------------------------------------
CREATE OR REPLACE TABLE FIELD_SYSTEMS_EDW.GENERAL.AG_PCS_AMORTIZED_DETAIL AS
SELECT
    a.RECEIVER_CODE,
    a.BILLING_MONTH,
    a.CARVEOUT,
    a.CARVEOUT_FC,
    a.TARGET_MONTH,
    a.MONTH_NUMBER,
    c.NATURAL_ACCOUNT,
    c.OTHER_BA
FROM FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_PCS_CARVEOUTS c
JOIN FIELD_SYSTEMS_EDW.GENERAL.PCS_CONFIG p
    ON c.RECEIVER_NAME = p.RECEIVER_CODE
    AND c.BILLING_MONTH = p.BILLING_MONTH
, TABLE(FIELD_SYSTEMS_EDW.GENERAL.AMORTIZED_PCS(
    c.RECEIVER_NAME,
    c.BILLING_MONTH,
    c.CARVEOUT_AMOUNT,
    p.MONTHS_IN_FUTURE,
    p.HALF_MONTH,
    p.LAG_MONTH
)) a;
