USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;
---------------------------------------------------------------------
-- 5. PCS_AMORTIZED_SUMMARY (Final Table)
-- Aggregates the materialized detail by receiver, with source months.
---------------------------------------------------------------------
CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.GENERAL.AG_PCS_AMORTIZED_SUMMARY AS
SELECT
    RECEIVER_CODE,
    NATURAL_ACCOUNT,
    OTHER_BA,
    SUM(CARVEOUT_FC) AS CARVEOUT_AMOUNT,
    LISTAGG(DISTINCT TO_CHAR(TARGET_MONTH, 'YYYY-MM-DD'), ', ') WITHIN GROUP (ORDER BY TO_CHAR(TARGET_MONTH, 'YYYY-MM-DD')) AS SOURCE_MONTHS
FROM FIELD_SYSTEMS_EDW.GENERAL.AG_PCS_AMORTIZED_DETAIL
GROUP BY RECEIVER_CODE, NATURAL_ACCOUNT, OTHER_BA
ORDER BY RECEIVER_CODE;