-- PCS carveout configuration, dynamic table, amortization UDF, and summary view
-- Co-authored with CoCo

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;
---------------------------------------------------------------------
-- 4. PCS_AMORTIZED_SUMMARY (View)
-- Aggregates amortized PCS carveouts by receiver and target month.
---------------------------------------------------------------------
CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.GENERAL.PCS_AMORTIZED_SUMMARY (
    RECEIVER_CODE,
    TARGET_MONTH,
    NATURAL_ACCOUNT,
    OTHER_BA,
    CARVEOUT_AMOUNT
) AS
SELECT
    c.RECEIVER_NAME AS RECEIVER_CODE,
    a.TARGET_MONTH,
    a.NATURAL_ACCOUNT,
    a.OTHER_BA,
    SUM(a.CARVEOUT_FC) AS CARVEOUT_AMOUNT
FROM TABLE(FIELD_SYSTEMS_EDW.GENERAL.AMORTIZED_PCS()) a
JOIN FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_PCS_CARVEOUTS c
    ON a.CURRENT_MONTH = c.BILLING_MONTH
    AND a.OTHER_BA = c.OTHER_BA
    AND a.NATURAL_ACCOUNT = c.NATURAL_ACCOUNT
GROUP BY c.RECEIVER_NAME, a.TARGET_MONTH, a.NATURAL_ACCOUNT, a.OTHER_BA
ORDER BY c.RECEIVER_NAME, a.TARGET_MONTH;