-- PCS carveout configuration, dynamic table, amortization UDF, and summary view
-- Co-authored with CoCo

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;
---------------------------------------------------------------------
-- 2. DYNAMIC_AG_PCS_CARVEOUTS
-- Calculates PCS carveout amounts per receiver and billing month.
---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_PCS_CARVEOUTS
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    s.RECEIVER_CODE AS RECEIVER_NAME,
    s.BILLINGS_MONTH AS BILLING_MONTH,
    CASE
        WHEN p.CARVE_PERCENTAGE IS NOT NULL
            THEN (p.CARVE_PERCENTAGE / 100) * r.RECEIVER_REVENUE
        ELSE p.DOLLAR_PER_UNIT * s.UNITS_SOLD
    END AS CARVEOUT_AMOUNT,
    p.NATURAL_ACCOUNT,
    p.OTHER_BA
FROM DYNAMIC_AG_UNIT_SALES_TABLE s
JOIN PCS_CONFIG p
    ON s.RECEIVER_CODE = p.RECEIVER_CODE
    AND s.BILLINGS_MONTH = p.BILLING_MONTH
JOIN DYNAMIC_AG_BOTTOMS_UP_REVENUE_FORECAST r
    ON s.RECEIVER_CODE = r.RECEIVER_CODE
    AND s.BILLINGS_MONTH = r.BILLINGS_MONTH;
