USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


create or replace TABLE FIELD_SYSTEMS_EDW.GENERAL.INTECH_CARVEOUTS_CONFIGURATION (
	RECEIVER_CODE VARCHAR(20),
    BILLINGS_MONTH VARCHAR(20),
	CARVEOUTS_PERCENTAGE NUMBER(10,2),
	CARVEOUTS_PRICE_PER_UNIT NUMBER(10,3)