USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE DYNAMIC_AG_INTECH_CARVEOUTS 
TARGET_LAG = '1 minute' 
REFRESH_MODE = FULL 
WAREHOUSE = GENERAL
AS
SELECT 
    s.RECEIVER_CODE AS RECEIVER_NAME, 
    s.BILLINGS_MONTH AS BILLING_MONTH, 
    CASE 
        WHEN p.CARVEOUTS_PERCENTAGE IS NOT NULL 
            THEN (p.CARVEOUTS_PERCENTAGE / 100) * 
                 CASE WHEN s.RECEIVER_CODE = 'NAV-900' THEN r.RECEIVER_REVENUE / 2 
                      ELSE r.RECEIVER_REVENUE END
        ELSE p.CARVEOUTS_PRICE_PER_UNIT * s.UNITS_SOLD 
    END AS CARVEOUT_AMOUNT
FROM DYNAMIC_AG_UNIT_SALES_TABLE s
JOIN INTECH_CARVEOUTS_CONFIGURATION p 
    ON s.RECEIVER_CODE = p.RECEIVER_CODE 
    AND s.BILLINGS_MONTH = p.BILLINGS_MONTH
JOIN DYNAMIC_AG_BOTTOMS_UP_REVENUE_FORECAST r 
    ON s.RECEIVER_CODE = r.RECEIVER_CODE 
    AND s.BILLINGS_MONTH = r.BILLINGS_MONTH;