USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_ADMIN_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


create schema if not exists FIELD_SYSTEMS_EDW.RAW_DATA;
create schema if not exists FIELD_SYSTEMS_EDW.BUSINESS_DATA;


CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK;
GRANT USAGE, CREATE TABLE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT USAGE, CREATE VIEW ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


GRANT OWNERSHIP ON TABLE FIELD_SYSTEMS_EDW.RAW_DATA.ONE_AG TO ROLE DOMO_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE FIELD_SYSTEMS_EDW.RAW_DATA.EBS_EXPENSE_DETAILS TO ROLE DOMO_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE FIELD_SYSTEMS_EDW.RAW_DATA.REVPRO_WATERFALL TO ROLE DOMO_INTEGRATION_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE REVOKE CURRENT GRANTS;

