USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_PCS
(
    RECEIVER_CODE,
    BILLING_MONTH,
    CARVEOUT_PERCENTAGE,
    RATE_PER_UNIT,
    MONTHS_IN_FUTURE,
    MONTH_LAG,
    HALF_MONTH,
    OTHER_BA,
    NATURAL_ACCOUNT
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    "3GXJMPESVB" AS RECEIVER_CODE,
    SPLIT_PART("PIS3KVXYC_", '-', 1) || '-' || LPAD(SPLIT_PART("PIS3KVXYC_", '-', 2), 2, '0') AS BILLING_MONTH,
    "M4YWGBJ2F-" AS CARVEOUT_PERCENTAGE,
    "34SM7WGDX-" AS RATE_PER_UNIT,
    "IDVBXBWDTH" AS MONTHS_IN_FUTURE,
    "XOWAU1DRYU" AS MONTH_LAG,
    CASE WHEN LOWER("1SKAJV6U_5") IN ('yes', 'y', 'true') THEN TRUE ELSE FALSE END AS HALF_MONTH,
    "PLBJV8VRWS" AS OTHER_BA,
    "B2WKG6Y68N" AS NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_f73e62e2_4752_46d2_af90_8a445fdb154e"
WHERE "3GXJMPESVB" IS NOT NULL
  AND TOMBSTONE_VERSION IS NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY "3GXJMPESVB", SPLIT_PART("PIS3KVXYC_", '-', 1) || '-' || LPAD(SPLIT_PART("PIS3KVXYC_", '-', 2), 2, '0')
    ORDER BY UPDATED_AT DESC
) = 1;
