USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_PCS
(
    RECEIVER_CODE,
    BILLING_MONTH,
    CARVEOUT_PERCENTAGE,
    RATE_PER_UNIT,
    MONTHS_IN_FUTURE,
    MONTH_LAG,
    HALF_MONTH,
    OTHER_BA,
    NATURAL_ACCOUNT
)
LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    "BD6AARRVWR" AS RECEIVER_CODE,
    "I3SLHS_TLU" AS BILLING_MONTH,
    "U77NPINTCP" AS CARVEOUT_PERCENTAGE,
    "_YVMBKEVWG" AS RATE_PER_UNIT,
    "NSC7SBHQII" AS MONTHS_IN_FUTURE,
    "-5HDKNLDGK" AS MONTH_LAG,
    "Z1WJFR6OJU" AS HALF_MONTH,
    "Q_JTLOZXQW" AS OTHER_BA,
    "BDAZ-NXYCG" AS NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_0b0c194d_8632_4474_890d_54ac5b2796c4"
WHERE "BD6AARRVWR" IS NOT NULL
  AND TOMBSTONE_VERSION IS NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY "BD6AARRVWR"
    ORDER BY UPDATED_AT DESC
) = 1;


--SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_RTX;