-- Filter expense actuals to current fiscal year months and summarize revenue
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;




CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_REVENUE_ACTUALS
  TARGET_LAG = '1 hour'
  WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT "Fiscal Period"
       , SUM("Amount USD") AS REVENUE
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_IDW_EXPENSE_DETAIL_ACTUALS
WHERE "P&L Category" = '1.REVENUE' 
  AND LEFT("Fiscal Period", 4) = YEAR(CURRENT_DATE)::VARCHAR
GROUP BY "Fiscal Period"
ORDER BY "Fiscal Period" ASC;

-- SELECT * FROM  FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_REVENUE_ACTUALS;