-- Use fiscal calendar to standardize fiscal period and calculate carveout
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;



CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_TOTAL_CARVEOUT_ACTUALS
    TARGET_LAG = '1 hour'
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    fc.FISCAL_MONTH_CODE,
    COALESCE(SUM(b.TOTAL_BILLINGS), 0) - ABS(SUM(r.REVENUE)) AS TOTAL_CARVEOUT
FROM (
    SELECT DISTINCT FISCAL_YEAR, FISCAL_MONTH, FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.GENERAL.DIMENSION_FISCAL_CALENDAR
) fc
LEFT JOIN FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_REVENUE_ACTUALS r
    ON r."Fiscal Period" = (YEAR(CURRENT_DATE()) * 100 + fc.FISCAL_MONTH)
LEFT JOIN (
    SELECT
        BILLINGS_MONTH,
        SUM(ACTUAL_REVENUE) AS TOTAL_BILLINGS
    FROM FIELD_SYSTEMS_EDW.GENERAL.AG_BILLINGS_ACTUALS
    GROUP BY BILLINGS_MONTH
) b
    ON b.BILLINGS_MONTH = REPLACE(fc.FISCAL_MONTH_CODE, '-', ' ')
WHERE r."Fiscal Period" IS NOT NULL
  AND fc.FISCAL_YEAR = YEAR(CURRENT_DATE())
GROUP BY fc.FISCAL_MONTH_CODE
ORDER BY fc.FISCAL_MONTH_CODE ASC;


SELECT * FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_TOTAL_CARVEOUT_ACTUALS;