---------------------------------------------------------------------
-- Bottoms Up COGS + OPEX Forecast Dynamic Table
-- Combines EXPENDITURE_AMOUNT from Total COGS and OPEX_AMOUNT from OPEX Manual Forecast
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_COGS_OPEX_FORECAST
    TARGET_LAG = DOWNSTREAM
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    BILLING_MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_AMOUNT
FROM (
    SELECT
        BILLING_MONTH,
        SUM(EXPENDITURE_AMOUNT) AS TOTAL_AMOUNT
    FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_COGS_FORECAST
    GROUP BY BILLING_MONTH

    UNION ALL

    SELECT
        BILLING_MONTH,
        SUM(OPEX_AMOUNT) AS TOTAL_AMOUNT
    FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OPEX_MANUAL_FORECAST
    GROUP BY BILLING_MONTH
)
GROUP BY BILLING_MONTH
ORDER BY BILLING_MONTH;
