USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

---------------------------------------------------------------------
-- VIEW_AG_RTX_AMORTIZED_SUMMARY
-- Aggregated amortization by receiver and target month.
---------------------------------------------------------------------
CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_AMORTIZED_SUMMARY AS
SELECT
    RECEIVER_CODE,
    TO_CHAR(TARGET_MONTH, 'YYYY-MM') AS TARGET_MONTH,
    SUM(CARVEOUT_AMOUNT_AMORTIZED) AS CARVEOUT_AMOUNT,
    OTHER_BA,
    NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_AMORTIZED_FORECAST
GROUP BY RECEIVER_CODE, TARGET_MONTH, OTHER_BA, NATURAL_ACCOUNT
ORDER BY RECEIVER_CODE, TARGET_MONTH;
