USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

---------------------------------------------------------------------
-- DYNAMIC_AG_RTX_AMORTIZED_FORECAST
-- Amortizes RTX carveout amounts into future fiscal months,
-- weighted by number of weeks per fiscal month.
---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_AMORTIZED_FORECAST
(
    RECEIVER_CODE,
    BILLING_MONTH,
    TARGET_MONTH,
    CARVEOUT_AMOUNT_AMORTIZED,
    OTHER_BA,
    NATURAL_ACCOUNT
)
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH carveout_base AS (
    SELECT
        c.RECEIVER_CODE,
        c.BILLING_MONTH,
        c.CARVEOUT_AMOUNT,
        c.OTHER_BA,
        c.NATURAL_ACCOUNT,
        COALESCE(p.MONTHS_IN_FUTURE, 0) AS MONTHS_IN_FUTURE,
        p.HALF_MONTH,
        COALESCE(p.MONTH_LAG, 0) AS MONTH_LAG
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_CARVEOUT_FORECAST c
    JOIN FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_RTX p
        ON c.RECEIVER_CODE = p.RECEIVER_CODE
        AND c.BILLING_MONTH = p.BILLING_MONTH
),
fiscal_months AS (
    SELECT
        FISCAL_MONTH_START AS MONTH_START,
        WEEKS_IN_MONTH,
        ROW_NUMBER() OVER (ORDER BY FISCAL_MONTH_START) AS MONTH_SEQ
    FROM (
        SELECT DISTINCT FISCAL_MONTH_START, WEEKS_IN_MONTH
        FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
        WHERE FISCAL_MONTH_START >= DATE_TRUNC('MONTH', CURRENT_DATE())
    )
),
expanded AS (
    SELECT
        cb.RECEIVER_CODE,
        cb.BILLING_MONTH,
        cb.CARVEOUT_AMOUNT,
        cb.OTHER_BA,
        cb.NATURAL_ACCOUNT,
        cb.HALF_MONTH,
        cb.MONTHS_IN_FUTURE,
        fm.WEEKS_IN_MONTH,
        SUM(fm.WEEKS_IN_MONTH) OVER (
            PARTITION BY cb.RECEIVER_CODE, cb.BILLING_MONTH
        ) AS TOTAL_WEEKS,
        fm.MONTH_START,
        fm.MONTH_SEQ - cb.MONTH_LAG AS MONTH_NUMBER
    FROM carveout_base cb
    JOIN fiscal_months fm
        ON fm.MONTH_SEQ BETWEEN cb.MONTH_LAG + 1
                              AND cb.MONTH_LAG + cb.MONTHS_IN_FUTURE + IFF(cb.HALF_MONTH = 'TRUE', 1, 0)
)
SELECT
    RECEIVER_CODE,
    BILLING_MONTH,
    MONTH_START AS TARGET_MONTH,
    CASE
        WHEN HALF_MONTH = 'TRUE' AND MONTH_NUMBER = 1
            THEN ROUND((CARVEOUT_AMOUNT / TOTAL_WEEKS) * WEEKS_IN_MONTH / 2, 5)
        WHEN HALF_MONTH = 'TRUE' AND MONTH_NUMBER = MONTHS_IN_FUTURE + 1
            THEN ROUND((CARVEOUT_AMOUNT / TOTAL_WEEKS) * WEEKS_IN_MONTH / 2, 5)
        ELSE ROUND((CARVEOUT_AMOUNT / TOTAL_WEEKS) * WEEKS_IN_MONTH, 5)
    END AS CARVEOUT_AMOUNT_AMORTIZED,
    OTHER_BA,
    NATURAL_ACCOUNT
FROM expanded
ORDER BY RECEIVER_CODE, BILLING_MONTH, MONTH_START;
