-- Filter expense actuals to current fiscal year months and summarize revenue
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;




CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_ACTUALS
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH CURRENT_FISCAL AS (
  SELECT FISCAL_YEAR, FISCAL_MONTH_CODE
  FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
  WHERE CALENDAR_DATE = CURRENT_DATE
)
SELECT e."Fiscal Month"
       , SUM(e."Amount USD") AS REVENUE
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_IDW_EXPENSE_DETAIL_ACTUALS e
CROSS JOIN CURRENT_FISCAL cf
WHERE e."P&L Category" = '1.REVENUE' AND e."GL Natural Account Description" LIKE '40030%'
  AND LEFT(e."Fiscal Month", 4) = cf.FISCAL_YEAR::VARCHAR
  AND e."Fiscal Month" < cf.FISCAL_MONTH_CODE
GROUP BY e."Fiscal Month"
ORDER BY e."Fiscal Month" ASC;

-- SELECT * FROM  FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_REVENUE_ACTUALS;