-- Dynamic tables: CONFIGURATION_AG_OCOGS and DYNAMIC_AG_OCOGS_FORECAST
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_OCOGS
(
    OCOGS_COMPONENT,
    BILLING_MONTH,
    EXPENDITURE_PERCENTAGE,
    RATE_PER_UNIT,
    OTHER_BA,
    NATURAL_ACCOUNT
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    "_H1YJSDOET" AS OCOGS_COMPONENT,
    "Y66BVQOJJG" AS BILLING_MONTH,
    "OJEKMDDQZN" AS EXPENDITURE_PERCENTAGE,
    "GSVVFXTDGB" AS RATE_PER_UNIT,
    "DMCMGBXW8O" AS OTHER_BA,
    "EIUZSWPVJ-" AS NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_8afaedf7_59c2_42b8_aeea_341d964c7436"
WHERE "_H1YJSDOET" IS NOT NULL
  AND TOMBSTONE_VERSION IS NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY UPPER("_H1YJSDOET"), "Y66BVQOJJG"
    ORDER BY UPDATED_AT DESC
) = 1;


SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_OCOGS




