-- Drop table DYNAMIC_AG_OCOGS_MANUAL_FORECAST
-- Co-authored with CoCo

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_MANUAL_LIST
  TARGET_LAG = '1 minute'
  REFRESH_MODE = FULL
  WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH latest_rows AS (
    SELECT
        s.H1NZXGRRCI,
        s.TOMBSTONE_VERSION,
        ROW_NUMBER() OVER (PARTITION BY s.ID ORDER BY s.ROW_VERSION DESC) AS rn
    FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_cb94680b_41af_4cc7_860a_d370d08f0477" s
)
SELECT DISTINCT
    H1NZXGRRCI AS OCOGS_COMPONENT,
    '40012' AS NATURAL_ACCOUNT,
    '553' AS OTHER_BA
FROM latest_rows
WHERE rn = 1
  AND TOMBSTONE_VERSION IS NULL
  AND H1NZXGRRCI IS NOT NULL
  AND TRIM(H1NZXGRRCI) <> ''






