USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA DISPLAY_AGIS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.DISPLAY_AGIS.VIEW_AG_OCOGS_FORECAST_STANDALONE AS

WITH current_period AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
)

SELECT
    OCOGS_COMPONENT AS COMPONENT_NAME,
    BILLING_MONTH,
    SUM(OCOGS_AMOUNT) AS AMOUNT,
    'FORECAST' AS SOURCE
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_OCOGS_FORECAST
CROSS JOIN current_period cp
WHERE BILLING_MONTH >= cp.FISCAL_MONTH_CODE
GROUP BY OCOGS_COMPONENT, BILLING_MONTH
ORDER BY COMPONENT_NAME, BILLING_MONTH;
