USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_MANUAL_FORECAST
(
  OCOGS_COMPONENT,
  BILLING_MONTH,
  OCOGS_AMOUNT,
  NATURAL_ACCOUNT,
  OTHER_BA
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH latest_per_component AS (
  SELECT
    "G8GF0QITFC" AS OCOGS_COMPONENT,
    "ZOGFLEFTIE" AS M01,
    "OFZEGAPWZZ" AS M02,
    "FPDD8OACBD" AS M03,
    "B6FTAED0WU" AS M04,
    "UEPDX82CXP" AS M05,
    "YD0OYAFHL5" AS M06,
    "KHE4ZBAB8L" AS M07,
    "RCSHEOBY9W" AS M08,
    "GFG5BJWQSA" AS M09,
    "TBXJOO3E1V" AS M10,
    "RQGXZP_NB7" AS M11,
    "B8DYEWWOLG" AS M12
  FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_229e8933_4786_4b8d_bc83_502441b76f4d"
  WHERE "G8GF0QITFC" IS NOT NULL
    AND TOMBSTONE_VERSION IS NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY "G8GF0QITFC"
    ORDER BY UPDATED_AT DESC
  ) = 1
),
current_fiscal_year AS (
  SELECT DISTINCT FISCAL_YEAR
  FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
  WHERE CALENDAR_DATE = CURRENT_DATE()
),
unpivoted AS (
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-01' AS BILLING_MONTH, M01 AS OCOGS_AMOUNT FROM latest_per_component, current_fiscal_year fy WHERE M01 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-02', M02 FROM latest_per_component, current_fiscal_year fy WHERE M02 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-03', M03 FROM latest_per_component, current_fiscal_year fy WHERE M03 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-04', M04 FROM latest_per_component, current_fiscal_year fy WHERE M04 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-05', M05 FROM latest_per_component, current_fiscal_year fy WHERE M05 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-06', M06 FROM latest_per_component, current_fiscal_year fy WHERE M06 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-07', M07 FROM latest_per_component, current_fiscal_year fy WHERE M07 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-08', M08 FROM latest_per_component, current_fiscal_year fy WHERE M08 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-09', M09 FROM latest_per_component, current_fiscal_year fy WHERE M09 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-10', M10 FROM latest_per_component, current_fiscal_year fy WHERE M10 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-11', M11 FROM latest_per_component, current_fiscal_year fy WHERE M11 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-12', M12 FROM latest_per_component, current_fiscal_year fy WHERE M12 IS NOT NULL
)
SELECT
  COALESCE(u.OCOGS_COMPONENT, d.OCOGS_COMPONENT) AS OCOGS_COMPONENT,
  u.BILLING_MONTH,
  u.OCOGS_AMOUNT,
  '40012' AS NATURAL_ACCOUNT,
  '553' AS OTHER_BA
FROM unpivoted u
FULL JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_MANUAL_LIST d
  ON u.OCOGS_COMPONENT = d.OCOGS_COMPONENT;


  SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_MANUAL_ENTRIES
