-- Dynamic tables: CONFIGURATION_AG_OCOGS and DYNAMIC_AG_OCOGS_FORECAST
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_OCOGS
(
    OCOGS_COMPONENT,
    BILLING_MONTH,
    EXPENDITURE_PERCENTAGE,
    RATE_PER_UNIT,
    OTHER_BA,
    NATURAL_ACCOUNT
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH latest_versions AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ROW_VERSION DESC) AS RN
    FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_0dadb84d_f4f3_450b_a531_120d16b587e0"
),
writeback AS (
    SELECT
        "1TJP-IOC9S" AS OCOGS_COMPONENT,
        SPLIT_PART("YV5MCKU6BZ", '-', 1) || '-' || LPAD(SPLIT_PART("YV5MCKU6BZ", '-', 2), 2, '0') AS BILLING_MONTH,
        CASE
            WHEN NULLIF(TRIM("GJG0UPMHGZ"::VARCHAR), '') IS NOT NULL THEN NULL
            ELSE "SZB4AO8CZJ"
        END AS EXPENDITURE_PERCENTAGE,
        TRY_CAST(REPLACE(REPLACE(NULLIF(TRIM("GJG0UPMHGZ"::VARCHAR), ''), '$', ''), ',', '') AS NUMBER(38,19)) AS RATE_PER_UNIT,
        "OT69E7GLTE" AS NATURAL_ACCOUNT,
        "R51REEEQTJ" AS OTHER_BA
    FROM latest_versions
    WHERE RN = 1
      AND TOMBSTONE_VERSION IS NULL
      AND "1TJP-IOC9S" IS NOT NULL
      AND TRIM("1TJP-IOC9S") <> ''
)
SELECT
    cl.OCOGS_COMPONENT,
    cl.BILLING_MONTH,
    w.EXPENDITURE_PERCENTAGE,
    w.RATE_PER_UNIT,
    COALESCE(w.OTHER_BA, 553) AS OTHER_BA,
    COALESCE(w.NATURAL_ACCOUNT, 4120) AS NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_COMPONENT_LIST cl
LEFT JOIN writeback w
    ON cl.OCOGS_COMPONENT = w.OCOGS_COMPONENT
    AND cl.BILLING_MONTH = w.BILLING_MONTH;


SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_OCOGS




