-- Dynamic table for AG OCOGS forecast using flat rate or expenditure percentage
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_OCOGS_FORECAST
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    c.BILLING_MONTH,
    c.OCOGS_COMPONENT,
    CASE
        WHEN c.RATE_PER_UNIT IS NOT NULL THEN c.RATE_PER_UNIT
        WHEN c.EXPENDITURE_PERCENTAGE IS NOT NULL THEN COALESCE(r.TOTAL_REVENUE, 0) * c.EXPENDITURE_PERCENTAGE / 100
    END AS OCOGS_AMOUNT,
    c.OTHER_BA,
    c.NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_OCOGS c
LEFT JOIN (
    SELECT
        BILLING_MONTH,
        SUM(BILLING_TOTAL) AS TOTAL_REVENUE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST
    GROUP BY BILLING_MONTH
) r ON c.BILLING_MONTH = r.BILLING_MONTH;


SELECT * FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_OCOGS_FORECAST
