-- Dimension AGIS Receivers --


-- Setup --
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Create DIMENSION_AGIS_RECEIVERS table --
CREATE TABLE IF NOT EXISTS FIELD_SYSTEMS_EDW.USER_INPUT.DIMENSION_AGIS_RECEIVERS (
    RECEIVER_CODE VARCHAR(50) NOT NULL,
    PRIMARY KEY (RECEIVER_CODE)
);


-- Seed data --
INSERT INTO FIELD_SYSTEMS_EDW.USER_INPUT.DIMENSION_AGIS_RECEIVERS (RECEIVER_CODE)
SELECT column1
FROM VALUES
    ('AG-200'),
    ('AG-392'),
    ('AG-482'),
    ('NAV-500'),
    ('NAV-860'),
    ('NAV-900'),
    ('NAV-960'),
    ('NAV-III'),
    ('TERRIER AG-960'),
    ('Z - MSDA')
WHERE column1 NOT IN (SELECT RECEIVER_CODE FROM FIELD_SYSTEMS_EDW.USER_INPUT.DIMENSION_AGIS_RECEIVERS);
