USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

---------------------------------------------------------------------
-- DYNAMIC_AG_RTX_AMORTIZED_FORECAST
-- Amortizes RTX carveout amounts into future fiscal months,
-- weighted by number of weeks per fiscal month.
---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_AMORTIZED_FORECAST
(
    RECEIVER_CODE,
    BILLING_MONTH,
    TARGET_MONTH,
    CARVEOUT_AMOUNT_AMORTIZED,
    OTHER_BA,
    NATURAL_ACCOUNT
)
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH carveout_base AS (
    SELECT
        c.RECEIVER_CODE,
        c.BILLING_MONTH,
        COALESCE(c.CARVEOUT_AMOUNT, 0) AS CARVEOUT_AMOUNT,
        c.OTHER_BA,
        c.NATURAL_ACCOUNT,
        COALESCE(p.MONTHS_IN_FUTURE, 0) AS MONTHS_IN_FUTURE,
        p.HALF_MONTH,
        COALESCE(p.MONTH_LAG, 0) AS MONTH_LAG
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_CARVEOUT_FORECAST c
    JOIN FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_RTX p
        ON c.RECEIVER_CODE = p.RECEIVER_CODE
        AND c.BILLING_MONTH = p.BILLING_MONTH
),
fiscal_months AS (
    SELECT
        FISCAL_MONTH_START AS MONTH_START,
        WEEKS_IN_MONTH,
        ROW_NUMBER() OVER (ORDER BY FISCAL_MONTH_START) AS MONTH_SEQ
    FROM (
        SELECT DISTINCT FISCAL_MONTH_START, WEEKS_IN_MONTH
        FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    )
),
billing_anchor AS (
    SELECT
        cb.*,
        fm.MONTH_SEQ AS BILLING_SEQ
    FROM carveout_base cb
    JOIN fiscal_months fm
        ON fm.MONTH_START <= TO_DATE(cb.BILLING_MONTH || '-01', 'YYYY-MM-DD')
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY cb.RECEIVER_CODE, cb.BILLING_MONTH, cb.OTHER_BA, cb.NATURAL_ACCOUNT
        ORDER BY fm.MONTH_START DESC
    ) = 1
),
expanded AS (
    SELECT
        ba.RECEIVER_CODE,
        ba.BILLING_MONTH,
        ba.CARVEOUT_AMOUNT,
        ba.OTHER_BA,
        ba.NATURAL_ACCOUNT,
        ba.HALF_MONTH,
        ba.MONTHS_IN_FUTURE,
        COALESCE(fm.WEEKS_IN_MONTH, 0) AS WEEKS_IN_MONTH,
        COALESCE(SUM(fm.WEEKS_IN_MONTH) OVER (
            PARTITION BY ba.RECEIVER_CODE, ba.BILLING_MONTH
        ), 0) AS TOTAL_WEEKS,
        fm.MONTH_START,
        fm.MONTH_SEQ - ba.BILLING_SEQ - ba.MONTH_LAG AS MONTH_NUMBER
    FROM billing_anchor ba
    JOIN fiscal_months fm
        ON fm.MONTH_SEQ BETWEEN ba.BILLING_SEQ + ba.MONTH_LAG + 1
                              AND ba.BILLING_SEQ + ba.MONTH_LAG + ba.MONTHS_IN_FUTURE + IFF(ba.HALF_MONTH = 'TRUE', 1, 0)
)
SELECT
    RECEIVER_CODE,
    BILLING_MONTH,
    MONTH_START AS TARGET_MONTH,
    CASE
        WHEN HALF_MONTH = 'TRUE' AND MONTH_NUMBER = 1
            THEN ROUND((CARVEOUT_AMOUNT / NULLIF(TOTAL_WEEKS, 0)) * WEEKS_IN_MONTH / 2, 5)
        WHEN HALF_MONTH = 'TRUE' AND MONTH_NUMBER = MONTHS_IN_FUTURE + 1
            THEN ROUND((CARVEOUT_AMOUNT / NULLIF(TOTAL_WEEKS, 0)) * WEEKS_IN_MONTH / 2, 5)
        ELSE ROUND((CARVEOUT_AMOUNT / NULLIF(TOTAL_WEEKS, 0)) * WEEKS_IN_MONTH, 5)
    END AS CARVEOUT_AMOUNT_AMORTIZED,
    OTHER_BA,
    NATURAL_ACCOUNT
FROM expanded
ORDER BY RECEIVER_CODE, BILLING_MONTH, MONTH_START;
