USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

---------------------------------------------------------------------
-- DYNAMIC_AG_RTX_CARVEOUT_FORECAST
-- Calculates RTX carveout amounts per receiver and billing month.
---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_CARVEOUT_FORECAST
(
    RECEIVER_CODE,
    BILLING_MONTH,
    CARVEOUT_AMOUNT,
    OTHER_BA,
    NATURAL_ACCOUNT
)
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    s.RECEIVER_CODE,
    s.BILLING_MONTH,
    CASE
        WHEN p.CARVEOUT_PERCENTAGE IS NOT NULL THEN
            CASE
                WHEN p.CARVEOUT_PERCENTAGE > 1 THEN (p.CARVEOUT_PERCENTAGE / 100)
                ELSE p.CARVEOUT_PERCENTAGE
            END * COALESCE(r.BILLING_TOTAL, 0)
        ELSE COALESCE(p.RATE_PER_UNIT, 0) * COALESCE(s.UNITS_SOLD, 0)
    END AS CARVEOUT_AMOUNT,
    p.OTHER_BA,
    p.NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVER_UNIT_SALES s
JOIN FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_RTX p
    ON s.RECEIVER_CODE = p.RECEIVER_CODE
    AND s.BILLING_MONTH = p.BILLING_MONTH
JOIN FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST r
    ON s.RECEIVER_CODE = r.RECEIVER_CODE
    AND s.BILLING_MONTH = r.BILLING_MONTH;
