USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA DISPLAY_AGIS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.DISPLAY_AGIS.VIEW_AG_RTX_CONSOLIDATED AS

WITH current_period AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),

actuals AS (
    SELECT
        "Fiscal Month" AS BILLING_MONTH,
        'UNIFIED' AS RECEIVER_CODE,
        REVENUE AS CARVEOUT_AMOUNT,
        'ACTUAL' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_ACTUALS
    CROSS JOIN current_period cp
    WHERE "Fiscal Month" < cp.FISCAL_MONTH_CODE
),

forecast AS (
    SELECT
        BILLING_MONTH,
        UPPER(RECEIVER_CODE) AS RECEIVER_CODE,
        SUM(CARVEOUT_AMOUNT) AS CARVEOUT_AMOUNT,
        'FORECAST' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_CARVEOUT_FORECAST
    CROSS JOIN current_period cp
    WHERE BILLING_MONTH >= cp.FISCAL_MONTH_CODE
    GROUP BY UPPER(RECEIVER_CODE), BILLING_MONTH
)

SELECT BILLING_MONTH, RECEIVER_CODE, CARVEOUT_AMOUNT, SOURCE
FROM actuals

UNION ALL

SELECT BILLING_MONTH, RECEIVER_CODE, CARVEOUT_AMOUNT, SOURCE
FROM forecast

ORDER BY RECEIVER_CODE, BILLING_MONTH;
