---------------------------------------------------------------------
-- Consolidated Expenditure Dynamic Table
-- Union of DCOGS, Intech, and OCOGS forecasts
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_COGS_FORECAST
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH MONTHS AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS BILLING_MONTH
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE FISCAL_YEAR = (
        SELECT FISCAL_YEAR
        FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
        WHERE CALENDAR_DATE = CURRENT_DATE
    )
),
EXPENDITURE_TYPES AS (
    SELECT 'DCOGS' AS EXPENDITURE_TYPE
    UNION ALL SELECT 'Intech'
    UNION ALL SELECT 'OCOGS'
    UNION ALL SELECT 'OCOGS_MANUAL'
),
MONTH_TYPES AS (
    SELECT m.BILLING_MONTH, t.EXPENDITURE_TYPE
    FROM MONTHS m
    CROSS JOIN EXPENDITURE_TYPES t
),
FORECASTS AS (
    SELECT 'DCOGS' AS EXPENDITURE_TYPE, BILLING_MONTH, SUM(EXPENDITURE_AMOUNT) AS EXPENDITURE_AMOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_DCOGS_FORECAST
    GROUP BY BILLING_MONTH
    UNION ALL
    SELECT 'Intech' AS EXPENDITURE_TYPE, BILLING_MONTH, SUM(CARVEOUT_AMOUNT) AS EXPENDITURE_AMOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_INTECH_FORECAST
    GROUP BY BILLING_MONTH
    UNION ALL
    SELECT 'OCOGS' AS EXPENDITURE_TYPE, BILLING_MONTH, SUM(OCOGS_AMOUNT) AS EXPENDITURE_AMOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_OCOGS_FORECAST
    GROUP BY BILLING_MONTH
    UNION ALL
    SELECT 'OCOGS_MANUAL' AS EXPENDITURE_TYPE, BILLING_MONTH, SUM(OCOGS_AMOUNT) AS EXPENDITURE_AMOUNT
    FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_MANUAL_FORECAST
    GROUP BY BILLING_MONTH
)
SELECT
    mt.EXPENDITURE_TYPE,
    mt.BILLING_MONTH,
    COALESCE(f.EXPENDITURE_AMOUNT, 0) AS EXPENDITURE_AMOUNT
FROM MONTH_TYPES mt
LEFT JOIN FORECASTS f ON mt.BILLING_MONTH = f.BILLING_MONTH AND mt.EXPENDITURE_TYPE = f.EXPENDITURE_TYPE
ORDER BY mt.EXPENDITURE_TYPE, mt.BILLING_MONTH;

SELECT * FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_COGS_FORECAST;