---------------------------------------------------------------------
-- Consolidated Expenditure Dynamic Table
-- Union of DCOGS and OCOGS actuals
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_COGS_ACTUALS
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH MONTHS AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS BILLING_MONTH
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE FISCAL_YEAR = (
        SELECT FISCAL_YEAR
        FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
        WHERE CALENDAR_DATE = CURRENT_DATE
    )
),
EXPENDITURE_TYPES AS (
    SELECT 'DCOGS' AS EXPENDITURE_TYPE
    UNION ALL
    SELECT 'OCOGS'
),
MONTH_TYPES AS (
    SELECT m.BILLING_MONTH, t.EXPENDITURE_TYPE
    FROM MONTHS m
    CROSS JOIN EXPENDITURE_TYPES t
),
ACTUALS AS (
    SELECT 'DCOGS' AS EXPENDITURE_TYPE, BILLING_MONTH, SUM(DCOGS_AMOUNT) AS EXPENDITURE_AMOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS
    GROUP BY BILLING_MONTH
    UNION ALL
    SELECT 'OCOGS' AS EXPENDITURE_TYPE, BILLING_MONTH, SUM(AMOUNT) AS EXPENDITURE_AMOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_OCOGS_ACTUALS
    GROUP BY BILLING_MONTH
)
SELECT
    mt.EXPENDITURE_TYPE,
    mt.BILLING_MONTH,
    COALESCE(a.EXPENDITURE_AMOUNT, 0) AS EXPENDITURE_AMOUNT
FROM MONTH_TYPES mt
LEFT JOIN ACTUALS a ON mt.BILLING_MONTH = a.BILLING_MONTH AND mt.EXPENDITURE_TYPE = a.EXPENDITURE_TYPE
ORDER BY mt.EXPENDITURE_TYPE, mt.BILLING_MONTH;
