-- Dynamic tables: CONFIGURATION_AG_OCOGS and DYNAMIC_AG_OCOGS_FORECAST
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_OCOGS
(
    OCOGS_COMPONENT,
    BILLING_MONTH,
    EXPENDITURE_PERCENTAGE,
    RATE_PER_UNIT,
    OTHER_BA,
    NATURAL_ACCOUNT
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    "W7XQQA3ME0" AS OCOGS_COMPONENT,
    "ZBLCHXKF0_" AS BILLING_MONTH,
    "COUE2TNI-K" AS EXPENDITURE_PERCENTAGE,
    "DHKVRVVPLR" AS RATE_PER_UNIT,
    "AM5GOOIDWL" AS OTHER_BA,
    "-M6WCJJ4J0" AS NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_966558e7_4eb3_4a30_8c45_54b86ee6d8e9"
WHERE "W7XQQA3ME0" IS NOT NULL
  AND TOMBSTONE_VERSION IS NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY UPPER("W7XQQA3ME0"), "ZBLCHXKF0_"
    ORDER BY UPDATED_AT DESC
) = 1;

SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_OCOGS





