USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_MANUAL_FORECAST
(
  OCOGS_COMPONENT,
  BILLING_MONTH,
  OCOGS_AMOUNT
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH latest_per_component AS (
  SELECT
    "Z0RZF-RZE-" AS OCOGS_COMPONENT,
    "AUVUMAGLQU" AS M01,
    "OGJXR4DDZN" AS M02,
    "BGHNJ7M0YK" AS M03,
    "RFVMSLK4BX" AS M04,
    "TFIPWAG8MA" AS M05,
    "3AC0RKMDCV" AS M06,
    "GY2J8XVINF" AS M07,
    "XD8KEGXYIY" AS M08,
    "EKAFQDKZ-S" AS M09,
    "Z36GTO6XRT" AS M10,
    "JGYGJXI6MF" AS M11,
    "RDD6X-SHHO" AS M12
  FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_1ba139e5_512e_4a97_a22f_4e207dd733be"
  WHERE "Z0RZF-RZE-" IS NOT NULL
    AND TOMBSTONE_VERSION IS NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY "Z0RZF-RZE-"
    ORDER BY UPDATED_AT DESC
  ) = 1
),
current_fiscal_year AS (
  SELECT DISTINCT FISCAL_YEAR
  FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
  WHERE CALENDAR_DATE = CURRENT_DATE()
),
unpivoted AS (
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-01' AS BILLING_MONTH, M01 AS OCOGS_AMOUNT FROM latest_per_component, current_fiscal_year fy WHERE M01 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-02', M02 FROM latest_per_component, current_fiscal_year fy WHERE M02 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-03', M03 FROM latest_per_component, current_fiscal_year fy WHERE M03 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-04', M04 FROM latest_per_component, current_fiscal_year fy WHERE M04 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-05', M05 FROM latest_per_component, current_fiscal_year fy WHERE M05 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-06', M06 FROM latest_per_component, current_fiscal_year fy WHERE M06 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-07', M07 FROM latest_per_component, current_fiscal_year fy WHERE M07 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-08', M08 FROM latest_per_component, current_fiscal_year fy WHERE M08 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-09', M09 FROM latest_per_component, current_fiscal_year fy WHERE M09 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-10', M10 FROM latest_per_component, current_fiscal_year fy WHERE M10 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-11', M11 FROM latest_per_component, current_fiscal_year fy WHERE M11 IS NOT NULL
  UNION ALL
  SELECT OCOGS_COMPONENT, fy.FISCAL_YEAR || '-12', M12 FROM latest_per_component, current_fiscal_year fy WHERE M12 IS NOT NULL
)
SELECT
  COALESCE(u.OCOGS_COMPONENT, d.OCOGS_COMPONENT) AS OCOGS_COMPONENT,
  u.BILLING_MONTH,
  u.OCOGS_AMOUNT
FROM unpivoted u
FULL JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_MANUAL_LIST d
  ON u.OCOGS_COMPONENT = d.OCOGS_COMPONENT;


  SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_MANUAL_ENTRIES
