-- Create INTECH_CARVEOUTS_CONFIGURATION table and DYNAMIC_AG_OCOGS_CARVEOUTS dynamic table
-- Co-authored with CoCo
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

-- Configuration table for carveouts
CREATE OR REPLACE TABLE FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_OCOGS (
    OCOGS_COMPONENT      VARCHAR(20),
    BILLING_MONTH       VARCHAR(20),
    CARVEOUTS_PERCENTAGE NUMBER(10,2),
    FLAT_RATE NUMBER(10,3),
    OTHER_BA INTEGER,
    NATURAL_ACCOUNT INTEGER,

    CONSTRAINT chk_mutual_exclusion CHECK (
        NOT (CARVEOUTS_PERCENTAGE IS NOT NULL AND FLAT_RATE IS NOT NULL)
    )
);
