-- Dynamic table for OCOGS carveouts and consolidated carveout view pivoted by billing month
-- Co-authored with CoCo
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;



-- Dynamic table that calculates OCOGS carveouts
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_OCOGS_FORECAST
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    c.BILLING_MONTH,
    c.OCOGS_COMPONENT,
    CASE
        WHEN c.FLAT_RATE IS NOT NULL THEN
            c.FLAT_RATE
        WHEN c.CARVEOUTS_PERCENTAGE IS NOT NULL THEN
            r.TOTAL_REVENUE * c.CARVEOUTS_PERCENTAGE / 100
    END AS OCOGS_CARVEOUTS,
    c.OTHER_BA,
    c.NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_OCOGS c
LEFT JOIN (
    SELECT BILLING_MONTH, SUM(BILLING_TOTAL) AS TOTAL_REVENUE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST
    GROUP BY BILLING_MONTH
) r
    ON c.BILLING_MONTH = r.BILLING_MONTH;