-- Recreate AG_OCOGS_COMPUTATION_LIST to read receiver codes from Sigma writeback table
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_COMPONENT_LIST(
    OCOGS_COMPONENT,
    BILLING_MONTH
) TARGET_LAG = '1 minute' REFRESH_MODE = FULL INITIALIZE = ON_CREATE WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH current_fiscal_year AS (
    SELECT DISTINCT FISCAL_YEAR
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),
receivers AS (
    SELECT DISTINCT "U2GNFMOA7Z" AS OCOGS_COMPONENT
    FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_fe6e223a_8d34_4168_8cba_7b33bb9b851e"
    WHERE "U2GNFMOA7Z" IS NOT NULL
      AND TOMBSTONE_VERSION IS NULL
),
months AS (
    SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS MONTH_NUM
    FROM TABLE(GENERATOR(ROWCOUNT => 12))
)
SELECT
    r.OCOGS_COMPONENT,
    fy.FISCAL_YEAR || '-' || LPAD(m.MONTH_NUM::VARCHAR, 2, '0') AS BILLING_MONTH
FROM receivers r
CROSS JOIN current_fiscal_year fy
CROSS JOIN months m


SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_COMPONENT_LIST;