USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_LIST
(
    OCOGS_ITEMS
)
LAG = '1 minute'
REFRESH_MODE = 'FULL'
INITIALIZE = 'ON_CREATE'
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT DISTINCT "YKFR_LDO0N" AS OCOGS_ITEMS
FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_7bbaee0e_71e9_422e_9183_6d61b778171a"
WHERE "YKFR_LDO0N" IS NOT NULL
  AND TOMBSTONE_VERSION IS NULL