USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_INTECH_FORECAST
(
    RECEIVER_CODE,
    BILLING_MONTH,
    CARVEOUT_AMOUNT,
    OTHER_BA,
    NATURAL_ACCOUNT  
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    c.RECEIVER_CODE,
    c.BILLING_MONTH,
    CASE
        WHEN c.CARVEOUTS_PERCENTAGE IS NOT NULL
            THEN (TRY_CAST(c.CARVEOUTS_PERCENTAGE AS NUMBER(10,4)) / 100) * r.BILLING_TOTAL
        WHEN c.RATE_PER_UNIT IS NOT NULL
            THEN c.RATE_PER_UNIT * TRY_CAST(s.UNITS_SOLD AS NUMBER(10,2))
    END AS CARVEOUT_AMOUNT,
    c.OTHER_BA,
    c.NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_INTECH c
LEFT JOIN FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST r
    ON c.RECEIVER_CODE = r.RECEIVER_CODE
    AND c.BILLING_MONTH = r.BILLING_MONTH
LEFT JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVER_UNIT_SALES s
    ON c.RECEIVER_CODE = s.RECEIVER_CODE
    AND c.BILLING_MONTH = s.BILLING_MONTH;