-- SCHEMA MANAGEMENT --


-- Setup --
USE ROLE FIELD_SYSTEMS_ADMIN_ROLE;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Create Schema --
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.BUSINESS_DATA;

CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK;
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.USER_INPUT;

CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT;
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT;
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT;

CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.DISPLAY_AGIS;
