-- User Access --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

-- DCL Commands --
GRANT ROLE FIELD_SYSTEMS_ADMIN_ROLE TO USER KKUMARA;
GRANT ROLE FIELD_SYSTEMS_DEVELOPER_ROLE TO USER KKUMARA;
GRANT ROLE SIGMA_INTEGRATION_ROLE TO USER KKUMARA;
GRANT ROLE DOMO_INTEGRATION_ROLE TO USER KKUMARA;

GRANT ROLE FIELD_SYSTEMS_ADMIN_ROLE TO USER VGUPTHA;
GRANT ROLE FIELD_SYSTEMS_DEVELOPER_ROLE TO USER VGUPTHA;
GRANT ROLE SIGMA_INTEGRATION_ROLE TO USER VGUPTHA;
GRANT ROLE DOMO_INTEGRATION_ROLE TO USER VGUPTHA;

GRANT ROLE FIELD_SYSTEMS_DEVELOPER_ROLE TO USER GARAVIN;
GRANT ROLE SIGMA_INTEGRATION_ROLE TO USER GARAVIN;
GRANT ROLE DOMO_INTEGRATION_ROLE TO USER GARAVIN;

GRANT ROLE FIELD_SYSTEMS_DEVELOPER_ROLE TO USER HGUGAN;
GRANT ROLE SIGMA_INTEGRATION_ROLE TO USER HGUGAN;
GRANT ROLE DOMO_INTEGRATION_ROLE TO USER HGUGAN;

GRANT ROLE FIELD_SYSTEMS_DEVELOPER_ROLE TO USER RMUCAJ;
GRANT ROLE SIGMA_INTEGRATION_ROLE TO USER RMUCAJ;

GRANT ROLE FIELD_SYSTEMS_DEVELOPER_ROLE TO USER TUTZMEI;
GRANT ROLE SIGMA_INTEGRATION_ROLE TO USER TUTZMEI;

GRANT ROLE FIELD_SYSTEMS_DEVELOPER_ROLE TO USER CMONROE;
GRANT ROLE SIGMA_INTEGRATION_ROLE TO USER CMONROE;
