-- FIELD_SYSTEMS_ADMIN_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Role creation --
CREATE ROLE IF NOT EXISTS FIELD_SYSTEMS_ADMIN_ROLE;


-- Grant OWNERSHIP to FIELD_SYSTEMS_ADMIN_ROLE --
GRANT OWNERSHIP ON WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE TO ROLE FIELD_SYSTEMS_ADMIN_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;


-- All privileges on all elements in all schemas, current and future --
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL DYNAMIC TABLES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE DYNAMIC TABLES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL STAGES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL PROCEDURES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL TASKS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TASKS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL STREAMS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT ALL PRIVILEGES ON ALL PIPES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PIPES IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;


GRANT ROLE FIELD_SYSTEMS_ADMIN_ROLE TO ROLE ACCOUNTADMIN;

-- Audit: show any grants beyond what this script defines
SHOW GRANTS TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;


ALTER TASK FIELD_SYSTEMS_EDW.OBSERVABILITY.REFRESH_COST_DATA_TASK SUSPEND;
ALTER TASK FIELD_SYSTEMS_EDW.OBSERVABILITY.REFRESH_COCO_USAGE_TASK SUSPEND;
