-- FIELD_SYSTEMS_DEVELOPER_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Role creation --
CREATE ROLE IF NOT EXISTS FIELD_SYSTEMS_DEVELOPER_ROLE;


-- Access Control --
GRANT USAGE ON DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT USAGE ON WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- SIGMA_WRITEBACK: all privileges on all current and future entities --
GRANT ALL PRIVILEGES ON SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- USER_INPUT: ownership on all current and future entities --
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PIPES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- COMPUTATIONAL_COMPONENT: ownership on all current and future entities --
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PIPES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- WORKFLOW_COMPONENT: ownership on all current and future entities --
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PIPES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- ARCHITECTURAL_COMPONENT: ownership on all current and future entities --
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PIPES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- BUSINESS_DATA: ownership on all current and future entities --
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PIPES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- GENERAL: ownership on all current and future entities --
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PIPES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- RAW_DATA: all privileges on all current and future entities --
GRANT ALL PRIVILEGES ON SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT ALL PRIVILEGES ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- Assign role --
GRANT ROLE FIELD_SYSTEMS_DEVELOPER_ROLE TO ROLE ACCOUNTADMIN;

-- Audit: show any grants beyond what this script defines
SHOW GRANTS TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
