-- SIGMA_INTEGRATION_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Create new warehouse matching SIGMA configuration --
CREATE WAREHOUSE IF NOT EXISTS FIELD_SYSTEMS_SIGMA_WAREHOUSE
    WAREHOUSE_SIZE = 'SMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    ENABLE_QUERY_ACCELERATION = TRUE
    QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE FIELD_SYSTEMS_SIGMA_WAREHOUSE;


-- OAuth Credentials
CREATE SECURITY INTEGRATION IF NOT EXISTS SIGMA_INTEGRATION_OAUTH
    TYPE = OAUTH
    ENABLED = TRUE
    OAUTH_CLIENT = CUSTOM
    OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'
    OAUTH_REDIRECT_URI = 'https://aws-api.sigmacomputing.com/api/v2/oauth/1/authcode'
    OAUTH_ISSUE_REFRESH_TOKENS = TRUE
    OAUTH_REFRESH_TOKEN_VALIDITY = 86400
    OAUTH_ENFORCE_PKCE = TRUE;

-- SELECT SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('SIGMA_INTEGRATION_OAUTH');


-- Role creation --
CREATE ROLE IF NOT EXISTS SIGMA_INTEGRATION_ROLE;


-- Access management --
GRANT USAGE ON DATABASE FIELD_SYSTEMS_EDW TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON INTEGRATION SIGMA_INTEGRATION_OAUTH TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON WAREHOUSE FIELD_SYSTEMS_SIGMA_WAREHOUSE TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;


-- SIGMA_WRITEBACK: ownership on all current and future entities --
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE;


-- USER_INPUT: usage on all current and future entities --
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE SIGMA_INTEGRATION_ROLE;


-- COMPUTATIONAL_COMPONENT: usage on all current and future entities --
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;


-- WORKFLOW_COMPONENT: usage on all current and future entities --
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT TO ROLE SIGMA_INTEGRATION_ROLE;


-- GENERAL: usage on all current and future entities --
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;


-- RAW_DATA: usage on all current and future entities --
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE SIGMA_INTEGRATION_ROLE;


GRANT ROLE SIGMA_INTEGRATION_ROLE TO ROLE ACCOUNTADMIN;


-- Audit: show any grants beyond what this script defines
SHOW GRANTS TO ROLE SIGMA_INTEGRATION_ROLE;
