-- Use fiscal calendar to standardize fiscal period and calculate carveout
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;





CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS_MARGIN
    TARGET_LAG = '1 hour'
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    b."GL Date Period ID" AS PERIOD_MONTH,
    b."Grouping",
    MAX(c."Item Cost") AS MAX_ITEM_COST
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_BILLINGS_PRICE_LIST_WITH_GROUPINGS_MODEL b
LEFT JOIN FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_FROZEN_COST_ARF c
    ON b."item" = c."Item"
INNER JOIN FIELD_SYSTEMS_EDW.GENERAL.DIMENSION_AGIS_RECEIVERS r
    ON UPPER(b."Grouping") = UPPER(r.RECEIVER_CODE)
GROUP BY b."GL Date Period ID", b."Grouping"
ORDER BY b."GL Date Period ID", b."Grouping";


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS
    TARGET_LAG = '1 hour'
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    d.PERIOD_MONTH,
    d."Grouping",
    d.MAX_ITEM_COST * SUM(b."Quantity Invoiced") AS DCOGS_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS_MARGIN d
INNER JOIN FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_BILLINGS_PRICE_LIST_WITH_GROUPINGS_MODEL b
    ON b."GL Date Period ID" = d.PERIOD_MONTH
    AND b."Grouping" = d."Grouping"
GROUP BY d.PERIOD_MONTH, d."Grouping", d.MAX_ITEM_COST
ORDER BY d.PERIOD_MONTH ASC, d."Grouping" ASC;



SELECT * FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS;