USE DATABASE FIELD_SYSTEMS_EDW;

USE SCHEMA USER_INPUT;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

-- Create DYNAMIC_AG_DCOGS table with receiver code, billings month, and amount columns
-- Co-authored with CoCo

CREATE OR REPLACE TABLE FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_DCOGS (
    RECEIVER_CODE VARCHAR,
    BILLING_MONTH VARCHAR(7),
    EXPENDITURE_PERCENTAGE NUMBER(18,4),
    RATE_PER_UNIT NUMBER(18,4),
    OTHER_BA VARCHAR,
    NATURAL_ACCOUNT VARCHAR,
  
    CONSTRAINT CHK_DCOGS_MUTUAL_EXCLUSIVITY CHECK (
        (DCOGS_PERCENTAGE IS NOT NULL AND DCOGS_PRICE_PER_UNIT IS NULL)
        OR (DCOGS_PERCENTAGE IS NULL AND DCOGS_PRICE_PER_UNIT IS NOT NULL)
    )
)