USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE DYNAMIC_AGIS_DCOGS
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
WAREHOUSE = GENERAL
AS
SELECT 
    s.RECEIVER_CODE AS RECEIVER_NAME, 
    s.BILLINGS_MONTH AS BILLING_MONTH, 
    CASE 
        WHEN p.DCOGS_PERCENTAGE IS NOT NULL 
            THEN (p.DCOGS_PERCENTAGE / 100) * r.RECEIVER_REVENUE
        ELSE p.DCOGS_PRICE_PER_UNIT * s.UNITS_SOLD 
    END AS AMOUNT,
    p.NATURAL_ACCOUNT,
    p.OTHER_BA
FROM DYNAMIC_AG_UNIT_SALES_TABLE s
JOIN AGIS_DCOGS_CONFIGURATION p 
    ON s.RECEIVER_CODE = p.RECEIVER_CODE 
    AND s.BILLINGS_MONTH = p.BILLINGS_MONTH
JOIN DYNAMIC_AG_BOTTOMS_UP_REVENUE_FORECAST r 
    ON s.RECEIVER_CODE = r.RECEIVER_CODE 
    AND s.BILLINGS_MONTH = r.BILLINGS_MONTH;