-- Create dynamic table DYNAMIC_AG_OPEX_MANUAL_ENTRIES with unpivoted monthly OPEX data
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OPEX_MANUAL_FORECAST
( OPEX_COMPONENT, BILLING_MONTH, OPEX_AMOUNT, NATURAL_ACCOUNT, OTHER_BA
)
LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH latest_per_component AS (
    SELECT
        "SE0AVLUNUC" AS OPEX_COMPONENT,
        "VJUFT5LJ-_" AS M01,
        "PB3QDVUYJH" AS M02,
        "IWZL_FWVI7" AS M03,
        "M1DYN5GZW2" AS M04,
        "8W3TEFA3W5" AS M05,
        "1NKSZTAUHK" AS M06,
        "JS1RICUHXK" AS M07,
        "8B7WBN5OAT" AS M08,
        "BG2Q5GJTDU" AS M09,
        "IJVURD9WVK" AS M10,
        "SYCCZGLCHH" AS M11,
        "2ISZY2QHRQ" AS M12
    FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_3d348285_5652_4835_9968_13de5146daa2"
    WHERE "SE0AVLUNUC" IS NOT NULL AND TOMBSTONE_VERSION IS NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY "SE0AVLUNUC"
        ORDER BY UPDATED_AT DESC
    ) = 1
),
current_fiscal_year AS (
    SELECT DISTINCT FISCAL_YEAR
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),
unpivoted AS (
    SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-01' AS BILLING_MONTH, M01 AS OPEX_AMOUNT FROM latest_per_component, current_fiscal_year fy WHERE M01 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-02', M02 FROM latest_per_component, current_fiscal_year fy WHERE M02 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-03', M03 FROM latest_per_component, current_fiscal_year fy WHERE M03 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-04', M04 FROM latest_per_component, current_fiscal_year fy WHERE M04 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-05', M05 FROM latest_per_component, current_fiscal_year fy WHERE M05 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-06', M06 FROM latest_per_component, current_fiscal_year fy WHERE M06 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-07', M07 FROM latest_per_component, current_fiscal_year fy WHERE M07 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-08', M08 FROM latest_per_component, current_fiscal_year fy WHERE M08 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-09', M09 FROM latest_per_component, current_fiscal_year fy WHERE M09 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-10', M10 FROM latest_per_component, current_fiscal_year fy WHERE M10 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-11', M11 FROM latest_per_component, current_fiscal_year fy WHERE M11 IS NOT NULL
    UNION ALL SELECT OPEX_COMPONENT, fy.FISCAL_YEAR || '-12', M12 FROM latest_per_component, current_fiscal_year fy WHERE M12 IS NOT NULL
)
SELECT
    COALESCE(u.OPEX_COMPONENT, d.OPEX_COMPONENT) AS OPEX_COMPONENT,
    u.BILLING_MONTH,
    u.OPEX_AMOUNT,
    '40012' AS NATURAL_ACCOUNT,
    '553' AS OTHER_BA
FROM unpivoted u
FULL JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OPEX_MANUAL_LIST d
    ON u.OPEX_COMPONENT = d.OPEX_COMPONENT;


  SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OPEX_MANUAL_ENTRIES