USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_OPEX_ACTUALS
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH CURRENT_FISCAL AS (
    SELECT FISCAL_YEAR, FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE
)
SELECT
    e."Fiscal Month" AS BILLING_MONTH,
    'OPEX' AS CATEGORY,
    e."PL Natural Account Summary" AS COMPONENT_NAME,
    SUM(e."Amount USD") AS AMOUNT
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_IDW_EXPENSE_DETAIL_ACTUALS e
CROSS JOIN CURRENT_FISCAL cf
WHERE e."P&L Category" = '4.OPEX'
  AND LEFT(e."Fiscal Month", 4) = cf.FISCAL_YEAR::VARCHAR
  AND e."Fiscal Month" < cf.FISCAL_MONTH_CODE
GROUP BY e."Fiscal Month", e."PL Natural Account Summary"
ORDER BY e."Fiscal Month" ASC, e."PL Natural Account Summary" ASC;
