-- Create dynamic table DYNAMIC_AG_OPEX_MANUAL_LIST from Sigma writeback OPEX components
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OPEX_MANUAL_LIST
  TARGET_LAG = '1 minute'
  REFRESH_MODE = FULL
  WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT DISTINCT
    s.XKYUWKZI3U AS OPEX_COMPONENT
FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_24993fe8_af5c_4302_8768_7842e9d0af1e" s
WHERE s.XKYUWKZI3U IS NOT NULL


SELECT * FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OPEX_MANUAL_LIST