USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

-- View: RTX_AMORTIZED_SUMMARY (aggregated amortization by target month with receiver code)
CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.GENERAL.RTX_AMORTIZED_SUMMARY AS
SELECT 
    c.RECEIVER_CODE,
    a.TARGET_MONTH,
    a.NATURAL_ACCOUNT,
    a.OTHER_BA,
    SUM(a.CARVEOUT_FC) AS CARVEOUT_AMOUNT
FROM FIELD_SYSTEMS_EDW.GENERAL.AMORTIZED_RTX a
JOIN FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_RTX_CARVEOUT c
    ON a.CURRENT_MONTH = c.CURRENT_MONTH
    AND a.OTHER_BA = c.BA
    AND a.NATURAL_ACCOUNT = c.NA
GROUP BY c.RECEIVER_CODE, a.TARGET_MONTH, a.NATURAL_ACCOUNT, a.OTHER_BA
ORDER BY c.RECEIVER_CODE, a.TARGET_MONTH;