USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Step 1: Recreate the failing upstream DT to reset its column types
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_COMPONENTS
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH billing_months AS (
    SELECT DISTINCT
        FISCAL_YEAR || '-' || LPAD(FISCAL_MONTH::VARCHAR, 2, '0') AS BILLING_MONTH,
        FISCAL_MONTH_START
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE FISCAL_YEAR = YEAR(CURRENT_DATE())
),
a_billings AS (
    SELECT
        BILLING_MONTH,
        SUM(BILLING_TOTAL) AS BILLINGS_TOTAL
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST
    GROUP BY BILLING_MONTH
),
b1_pcs_carveout AS (
    SELECT
        BILLING_MONTH,
        SUM(CARVEOUT_AMOUNT) AS PCS_CARVEOUT,
        MAX(OTHER_BA) AS OTHER_BA,
        MAX(NATURAL_ACCOUNT) AS NATURAL_ACCOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_PCS_CARVEOUT_FORECAST
    GROUP BY BILLING_MONTH
),
b2_rtx_carveout AS (
    SELECT
        BILLING_MONTH,
        SUM(CARVEOUT_AMOUNT) AS RTX_CARVEOUT,
        MAX(OTHER_BA) AS OTHER_BA,
        MAX(NATURAL_ACCOUNT) AS NATURAL_ACCOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_CARVEOUT_FORECAST
    GROUP BY BILLING_MONTH
),
target_month_map AS (
    SELECT DISTINCT
        FISCAL_MONTH_START,
        FISCAL_YEAR || '-' || LPAD(FISCAL_MONTH::VARCHAR, 2, '0') AS TARGET_BILLING_MONTH
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
),
current_fiscal AS (
    SELECT DISTINCT
        FISCAL_YEAR || '-' || LPAD(FISCAL_MONTH::VARCHAR, 2, '0') AS CURRENT_BILLING_MONTH
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),
c1_pcs_forecast AS (
    SELECT
        tm.TARGET_BILLING_MONTH AS BILLING_MONTH,
        SUM(paf.CARVEOUT_AMOUNT_AMORTIZED) AS PCS_AMORTIZED_FROM_PAST
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_PCS_AMORTIZED_FORECAST paf
    JOIN target_month_map tm
        ON TRY_TO_DATE(REPLACE(paf.TARGET_MONTH, '"', '')) = tm.FISCAL_MONTH_START
    WHERE tm.TARGET_BILLING_MONTH > (SELECT CURRENT_BILLING_MONTH FROM current_fiscal)
    GROUP BY tm.TARGET_BILLING_MONTH
),
c1_pcs_actuals AS (
    SELECT
        YEAR(CURRENT_DATE())::VARCHAR || '-' || RIGHT(f.key, 2) AS BILLING_MONTH,
        SUM(f.value::FLOAT) AS PCS_AMORTIZED_FROM_PAST
    FROM (SELECT OBJECT_CONSTRUCT(*) AS obj FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_WATERFALL) src,
    LATERAL FLATTEN(input => src.obj) f
    WHERE f.key LIKE '%-M%'
    GROUP BY f.key
),
c1_combined AS (
    SELECT BILLING_MONTH, PCS_AMORTIZED_FROM_PAST
    FROM c1_pcs_actuals
    WHERE BILLING_MONTH <= (SELECT CURRENT_BILLING_MONTH FROM current_fiscal)
    UNION ALL
    SELECT BILLING_MONTH, PCS_AMORTIZED_FROM_PAST
    FROM c1_pcs_forecast
),
c2_rtx_forecast AS (
    SELECT
        tm.TARGET_BILLING_MONTH AS BILLING_MONTH,
        SUM(raf.CARVEOUT_AMOUNT_AMORTIZED) AS RTX_AMORTIZED_FROM_PAST
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_RTX_AMORTIZED_FORECAST raf
    JOIN target_month_map tm
        ON TRY_TO_DATE(REPLACE(raf.TARGET_MONTH, '"', '')) = tm.FISCAL_MONTH_START
    WHERE tm.TARGET_BILLING_MONTH > (SELECT CURRENT_BILLING_MONTH FROM current_fiscal)
    GROUP BY tm.TARGET_BILLING_MONTH
),
c2_rtx_actuals AS (
    SELECT
        YEAR(CURRENT_DATE())::VARCHAR || '-' || RIGHT(f.key, 2) AS BILLING_MONTH,
        SUM(f.value::FLOAT) AS RTX_AMORTIZED_FROM_PAST
    FROM (SELECT OBJECT_CONSTRUCT(*) AS obj FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_RTX_WATERFALL) src,
    LATERAL FLATTEN(input => src.obj) f
    WHERE f.key LIKE '%-M%'
    GROUP BY f.key
),
c2_combined AS (
    SELECT BILLING_MONTH, RTX_AMORTIZED_FROM_PAST
    FROM c2_rtx_actuals
    WHERE BILLING_MONTH <= (SELECT CURRENT_BILLING_MONTH FROM current_fiscal)
    UNION ALL
    SELECT BILLING_MONTH, RTX_AMORTIZED_FROM_PAST
    FROM c2_rtx_forecast
)
SELECT
    bm.BILLING_MONTH,
    COALESCE(a.BILLINGS_TOTAL, 0) AS BILLINGS_TOTAL,
    COALESCE(b1.PCS_CARVEOUT, 0) AS PCS_CARVEOUT,
    COALESCE(b2.RTX_CARVEOUT, 0) AS RTX_CARVEOUT,
    COALESCE(c1.PCS_AMORTIZED_FROM_PAST, 0) AS PCS_AMORTIZED_FROM_PAST,
    COALESCE(c2.RTX_AMORTIZED_FROM_PAST, 0) AS RTX_AMORTIZED_FROM_PAST,
    COALESCE(b1.OTHER_BA, b2.OTHER_BA) AS OTHER_BA,
    COALESCE(b1.NATURAL_ACCOUNT, b2.NATURAL_ACCOUNT) AS NATURAL_ACCOUNT
FROM billing_months bm
LEFT JOIN a_billings a ON bm.BILLING_MONTH = a.BILLING_MONTH
LEFT JOIN b1_pcs_carveout b1 ON bm.BILLING_MONTH = b1.BILLING_MONTH
LEFT JOIN b2_rtx_carveout b2 ON bm.BILLING_MONTH = b2.BILLING_MONTH
LEFT JOIN c1_combined c1 ON bm.BILLING_MONTH = c1.BILLING_MONTH
LEFT JOIN c2_combined c2 ON bm.BILLING_MONTH = c2.BILLING_MONTH
ORDER BY bm.BILLING_MONTH;


-- Step 2: Recreate the intermediate DT that depends on the above
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_FORECAST
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    BILLING_MONTH,
    BILLINGS_TOTAL - (PCS_CARVEOUT + RTX_CARVEOUT) + (PCS_AMORTIZED_FROM_PAST + RTX_AMORTIZED_FROM_PAST) AS TOTAL_REVENUE,
    OTHER_BA,
    NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_COMPONENTS
ORDER BY BILLING_MONTH;


-- Step 3: Recreate the target DT (your original table, unchanged)
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_OPERATING_EXPENDITURE_FORECAST
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH current_period AS (
    SELECT DISTINCT FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),
billings_actuals AS (
    SELECT
        BILLINGS_MONTH AS BILLING_MONTH,
        UPPER(RECEIVER_CODE) AS RECEIVER_CODE,
        ACTUAL_REVENUE AS REVENUE,
        'ACTUAL' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_BOTTOMS_UP_BILLINGS_ACTUALS
    CROSS JOIN current_period cp
    WHERE BILLINGS_MONTH < cp.FISCAL_MONTH_CODE
),
billings_forecast AS (
    SELECT
        LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) AS BILLING_MONTH,
        UPPER(RECEIVER_CODE) AS RECEIVER_CODE,
        BILLING_TOTAL AS REVENUE,
        'FORECAST' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST
    CROSS JOIN current_period cp
    WHERE LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) >= cp.FISCAL_MONTH_CODE
),
billings_consolidated AS (
    SELECT BILLING_MONTH, RECEIVER_CODE, REVENUE, SOURCE FROM billings_actuals
    UNION ALL
    SELECT BILLING_MONTH, RECEIVER_CODE, REVENUE, SOURCE FROM billings_forecast
),
billings AS (
    SELECT
        BILLING_MONTH,
        SUM(REVENUE) AS TOTAL_BILLINGS_REVENUE
    FROM billings_consolidated
    GROUP BY BILLING_MONTH
),
cogs AS (
    SELECT
        LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) AS BILLING_MONTH,
        SUM(EXPENDITURE_AMOUNT) AS TOTAL_COGS
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_TOTAL_COGS_ACTUALS
    GROUP BY BILLING_MONTH
),
opex AS (
    SELECT
        LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) AS BILLING_MONTH,
        SUM(TOTAL_AMOUNT) AS TOTAL_OPEX
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_TOTAL_OPEX_ACTUALS
    GROUP BY BILLING_MONTH
),
revenue_actuals AS (
    SELECT "Fiscal Month" AS BILLING_MONTH, REVENUE, 'ACTUAL' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_REVENUE_ACTUALS
    CROSS JOIN current_period cp
    WHERE "Fiscal Month" < cp.FISCAL_MONTH_CODE
),
revenue_forecast AS (
    SELECT LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) AS BILLING_MONTH, TOTAL_REVENUE AS REVENUE, 'FORECAST' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_REVENUE_FORECAST
    CROSS JOIN current_period cp
    WHERE LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) >= cp.FISCAL_MONTH_CODE
),
revenue_consolidated AS (
    SELECT BILLING_MONTH, REVENUE, SOURCE FROM revenue_actuals
    UNION ALL
    SELECT BILLING_MONTH, REVENUE, SOURCE FROM revenue_forecast
),
base_months AS (
    SELECT DISTINCT BILLING_MONTH
    FROM revenue_consolidated
)
SELECT
    bm.BILLING_MONTH,
    (COALESCE(b.TOTAL_BILLINGS_REVENUE, 0) - COALESCE(c.TOTAL_COGS, 0) - COALESCE(o.TOTAL_OPEX, 0)) AS TOTAL_REVENUE
FROM base_months bm
LEFT JOIN billings b ON bm.BILLING_MONTH = b.BILLING_MONTH
LEFT JOIN cogs c ON bm.BILLING_MONTH = c.BILLING_MONTH
LEFT JOIN opex o ON bm.BILLING_MONTH = o.BILLING_MONTH
ORDER BY bm.BILLING_MONTH ASC;