---------------------------------------------------------------------
-- Consolidated Expenditure Dynamic Table
-- Union of DCOGS, Intech, and OCOGS forecasts
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_OCOGS_FORECAST
    TARGET_LAG = DOWNSTREAM
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    'DCOGS' AS EXPENDITURE_TYPE,
    BILLING_MONTH,
    SUM(EXPENDITURE_AMOUNT) AS EXPENDITURE_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_DCOGS_FORECAST
GROUP BY BILLING_MONTH

UNION ALL

SELECT
    'Intech' AS EXPENDITURE_TYPE,
    BILLING_MONTH,
    SUM(CARVEOUT_AMOUNT) AS EXPENDITURE_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_INTECH_FORECAST
GROUP BY BILLING_MONTH

UNION ALL

SELECT
    'OCOGS' AS EXPENDITURE_TYPE,
    BILLING_MONTH,
    SUM(OCOGS_CARVEOUTS) AS EXPENDITURE_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_OCOGS_FORECAST
GROUP BY BILLING_MONTH

UNION ALL

SELECT
    'OCOGS_MANUAL' AS EXPENDITURE_TYPE,
    BILLING_MONTH,
    SUM(OCOGS_AMOUNT) AS EXPENDITURE_AMOUNT
FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OCOGS_MANUAL_FORECAST
GROUP BY BILLING_MONTH

ORDER BY EXPENDITURE_TYPE, BILLING_MONTH;
