---------------------------------------------------------------------
-- Consolidated Expenditure Dynamic Table
-- Union of DCOGS and OCOGS actuals
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_COGS_ACTUALS
    TARGET_LAG = DOWNSTREAM
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    'DCOGS' AS EXPENDITURE_TYPE,
    BILLING_MONTH,
    SUM(DCOGS_AMOUNT) AS EXPENDITURE_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS
GROUP BY BILLING_MONTH

UNION ALL

SELECT
    'OCOGS' AS EXPENDITURE_TYPE,
    LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) AS BILLING_MONTH,
    SUM(AMOUNT) AS EXPENDITURE_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_OCOGS_ACTUALS
GROUP BY LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2)

ORDER BY EXPENDITURE_TYPE, BILLING_MONTH;
