---------------------------------------------------------------------
-- Consolidated Expenditure View
-- Union of Intech, OCOGS, and DCOGS forecasts
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA DISPLAY_AGIS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.DISPLAY_AGIS.VIEW_AG_OCOGS_PX AS

SELECT
    'Intech' AS EXPENDITURE_TYPE,
    BILLING_MONTH,
    SUM(CARVEOUT_AMOUNT) AS EXPENDITURE_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_INTECH_FORECAST
GROUP BY BILLING_MONTH

UNION ALL

SELECT
    'OCOGS' AS EXPENDITURE_TYPE,
    BILLING_MONTH,
    SUM(OCOGS_CARVEOUTS) AS EXPENDITURE_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_OCOGS_FORECAST
GROUP BY BILLING_MONTH

UNION ALL

SELECT
    'DCOGS' AS EXPENDITURE_TYPE,
    BILLING_MONTH,
    SUM(EXPENDITURE_AMOUNT) AS EXPENDITURE_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_DCOGS_FORECAST
GROUP BY BILLING_MONTH

ORDER BY EXPENDITURE_TYPE, BILLING_MONTH;
