USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

---------------------------------------------------------------------
-- VIEW_AG_PCS_AMORTIZED_SUMMARY
-- Aggregated amortization by receiver and target month.
---------------------------------------------------------------------
CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_PCS_AMORTIZED_SUMMARY AS
SELECT
    f.RECEIVER_CODE,
    TO_CHAR(f.TARGET_MONTH, 'YYYY-MM') AS TARGET_MONTH,
    SUM(f.CARVEOUT_AMOUNT_AMORTIZED) AS CARVEOUT_AMOUNT,
    f.OTHER_BA,
    f.NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_PCS_AMORTIZED_FORECAST f
LEFT JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVERS_LIST r
    ON f.RECEIVER_CODE = r.RECEIVER_CODE
GROUP BY f.RECEIVER_CODE, f.TARGET_MONTH, f.OTHER_BA, f.NATURAL_ACCOUNT, r.SORT_ORDER
ORDER BY r.SORT_ORDER, TARGET_MONTH;
