USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_TOTAL_COGS_ACTUALS
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    BILLING_MONTH,
    EXPENDITURE_TYPE,
    EXPENDITURE_AMOUNT
FROM (
    SELECT REPLACE(BILLING_MONTH, '-M', '-') AS BILLING_MONTH, 'DCOGS' AS EXPENDITURE_TYPE, SUM(DCOGS_AMOUNT) AS EXPENDITURE_AMOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS
    GROUP BY BILLING_MONTH

    UNION ALL

    SELECT LEFT(CAST(BILLING_MONTH AS VARCHAR(6)), 4) || '-' || RIGHT(CAST(BILLING_MONTH AS VARCHAR(6)), 2) AS BILLING_MONTH, 'OCOGS' AS EXPENDITURE_TYPE, SUM(AMOUNT) AS EXPENDITURE_AMOUNT
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_OCOGS_ACTUALS
    GROUP BY BILLING_MONTH
);