USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_TOTAL_COGS_ACTUALS
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    o.BILLING_MONTH,
    NVL(d.DCOGS_TOTAL, 0) + NVL(o.OCOGS_TOTAL, 0) AS EXPENDITURE_AMOUNT
FROM (
    SELECT BILLING_MONTH, SUM(AMOUNT) AS OCOGS_TOTAL
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_OCOGS_ACTUALS
    GROUP BY BILLING_MONTH
) o
LEFT JOIN (
    SELECT BILLING_MONTH, SUM(DCOGS_AMOUNT) AS DCOGS_TOTAL
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_DCOGS_ACTUALS
    GROUP BY BILLING_MONTH
) d
    ON o.BILLING_MONTH = d.BILLING_MONTH
ORDER BY o.BILLING_MONTH ASC;
