USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA DISPLAY_AGIS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.DISPLAY_AGIS.VIEW_AG_BOTTOMS_UP_BILLINGS_CONSOLIDATED AS

WITH current_period AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),

actuals AS (
    SELECT
        BILLINGS_MONTH AS BILLING_MONTH,
        UPPER(RECEIVER_CODE) AS RECEIVER_CODE,
        ACTUAL_BILLING AS REVENUE,
        'ACTUAL' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_BOTTOMS_UP_BILLINGS_ACTUALS
    CROSS JOIN current_period cp
    WHERE BILLINGS_MONTH < cp.FISCAL_MONTH_CODE
),

forecast AS (
    SELECT
        BILLING_MONTH,
        UPPER(RECEIVER_CODE) AS RECEIVER_CODE,
        BILLING_TOTAL AS REVENUE,
        'FORECAST' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST
    CROSS JOIN current_period cp
    WHERE BILLING_MONTH >= cp.FISCAL_MONTH_CODE
),

combined AS (
    SELECT BILLING_MONTH, RECEIVER_CODE, REVENUE, SOURCE
    FROM actuals

    UNION ALL

    SELECT BILLING_MONTH, RECEIVER_CODE, REVENUE, SOURCE
    FROM forecast
)

SELECT c.BILLING_MONTH, c.RECEIVER_CODE, c.REVENUE, c.SOURCE
FROM combined c
LEFT JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVERS_LIST r
    ON UPPER(c.RECEIVER_CODE) = UPPER(r.RECEIVER_CODE)
ORDER BY r.SORT_ORDER, c.BILLING_MONTH;
