-- Replicate PCS waterfall pattern for RTX
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;



CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_RTX_WATERFALL AS
SELECT
    SUM("Jan_26") AS "Jan_26",
    SUM("Feb_26") AS "Feb_26",
    SUM("Mar_26") AS "Mar_26",
    SUM("Apr_26") AS "Apr_26",
    SUM("May_26") AS "May_26",
    SUM("Jun_26") AS "Jun_26",
    SUM("Jul_26") AS "Jul_26",
    SUM("Aug_26") AS "Aug_26",
    SUM("Sep_26") AS "Sep_26",
    SUM("Oct_26") AS "Oct_26",
    SUM("Nov_26") AS "Nov_26",
    SUM("Dec_26") AS "Dec_26"
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.RTX_Carveout;

-- SELECT * FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_RTX_WATERFALL;

