USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

-- View: AG_AMORTIZED_RTX_SUMMARY (aggregated amortization by target month with receiver code)
CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.GENERAL.AG_AMORTIZED_RTX_SUMMARY AS
SELECT 
    c.RECEIVER_CODE,
    a.TARGET_MONTH,
    SUM(a.CARVEOUT_FC) AS CARVEOUT_AMOUNT,
    a.NATURAL_ACCOUNT,
    a.OTHER_BA
FROM FIELD_SYSTEMS_EDW.GENERAL.AG_AMORTIZED_RTX a
JOIN FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_RTX_CARVEOUTS c
    ON a.CURRENT_MONTH = c.CURRENT_MONTH
    AND a.OTHER_BA = c.OTHER_BA
    AND a.NATURAL_ACCOUNT = c.NATURAL_ACCOUNT
    AND a.CARVEOUT = c.CARVEOUT
GROUP BY c.RECEIVER_CODE, a.TARGET_MONTH, a.NATURAL_ACCOUNT, a.OTHER_BA
ORDER BY c.RECEIVER_CODE, a.TARGET_MONTH;