USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

-- Separate Table: AG_AMORTIZED_RTX (amortization of carveout into fiscal months)
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.GENERAL.AG_AMORTIZED_RTX (
    RECEIVER_CODE,
    CURRENT_MONTH,
    CARVEOUT,
    CARVEOUT_FC,
    TARGET_MONTH,
    NATURAL_ACCOUNT,
    OTHER_BA
) TARGET_LAG = '1 minute' REFRESH_MODE = FULL INITIALIZE = ON_CREATE WAREHOUSE = GENERAL
AS
WITH carveout_base AS (
    SELECT 
        c.RECEIVER_CODE,
        c.CURRENT_MONTH,
        c.CARVEOUT,
        c.OTHER_BA,
        c.NATURAL_ACCOUNT,
        p.MONTHS_IN_FUTURE,
        p.HALF_MONTH,
        p.LAG_MONTH
    FROM FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_RTX_CARVEOUTS c
JOIN FIELD_SYSTEMS_EDW.GENERAL.AG_RTX_CONFIGURATION p 
        ON c.RECEIVER_CODE = p.RECEIVER_CODE 
        AND c.CURRENT_MONTH = p.CURRENT_MONTH
),
fiscal_months AS (
    SELECT 
        FISCAL_MONTH_START AS MONTH_START,
        ROW_NUMBER() OVER (ORDER BY FISCAL_MONTH_START) AS MONTH_SEQ
    FROM (
        SELECT DISTINCT FISCAL_MONTH_START 
        FROM FIELD_SYSTEMS_EDW.GENERAL.DIMENSION_FISCAL_CALENDAR
        WHERE FISCAL_MONTH_START >= DATE_TRUNC('MONTH', CURRENT_DATE())
    )
),
expanded AS (
    SELECT 
        cb.RECEIVER_CODE,
        cb.CURRENT_MONTH,
        cb.CARVEOUT,
        cb.OTHER_BA,
        cb.NATURAL_ACCOUNT,
        cb.HALF_MONTH,
        cb.MONTHS_IN_FUTURE,
        ROUND(cb.CARVEOUT / cb.MONTHS_IN_FUTURE, 2) AS BASE_AMOUNT,
        fm.MONTH_START,
        fm.MONTH_SEQ - cb.LAG_MONTH AS MONTH_NUMBER
    FROM carveout_base cb
    JOIN fiscal_months fm
        ON fm.MONTH_SEQ BETWEEN cb.LAG_MONTH + 1 
                              AND cb.LAG_MONTH + cb.MONTHS_IN_FUTURE + IFF(cb.HALF_MONTH, 1, 0)
)
SELECT 
    RECEIVER_CODE,
    CURRENT_MONTH,
    CARVEOUT,
    CASE 
        WHEN HALF_MONTH AND MONTH_NUMBER = 1 THEN ROUND(BASE_AMOUNT / 2, 2)
        WHEN HALF_MONTH AND MONTH_NUMBER = MONTHS_IN_FUTURE + 1 THEN ROUND(BASE_AMOUNT / 2, 2)
        ELSE BASE_AMOUNT
    END AS CARVEOUT_FC,
    MONTH_START AS TARGET_MONTH,
    NATURAL_ACCOUNT,
    OTHER_BA
FROM expanded
ORDER BY RECEIVER_CODE, CURRENT_MONTH, MONTH_START;