USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

-- Dynamic Table: DYNAMIC_AG_RTX_CARVEOUTS (without amortization columns)
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_RTX_CARVEOUTS (
    RECEIVER_CODE,
    CURRENT_MONTH,
    CARVEOUT,
    OTHER_BA,
    NATURAL_ACCOUNT
) TARGET_LAG = '1 minute' REFRESH_MODE = FULL INITIALIZE = ON_CREATE WAREHOUSE = GENERAL
AS
SELECT 
    s.RECEIVER_CODE,
    s.BILLINGS_MONTH AS CURRENT_MONTH,
    CASE 
        WHEN p.RTX_PERCENTAGE IS NOT NULL 
            THEN (p.RTX_PERCENTAGE / 100) * r.RECEIVER_REVENUE
        ELSE p.RTX_PRICE_PER_UNIT * s.UNITS_SOLD 
    END AS CARVEOUT,
    p.OTHER_BA,
    p.NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_UNIT_SALES_TABLE s
JOIN FIELD_SYSTEMS_EDW.GENERAL.AG_RTX_CONFIGURATION p 
    ON s.RECEIVER_CODE = p.RECEIVER_CODE 
    AND s.BILLINGS_MONTH = p.CURRENT_MONTH
JOIN FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_BOTTOMS_UP_REVENUE_FORECAST r 
    ON s.RECEIVER_CODE = r.RECEIVER_CODE 
    AND s.BILLINGS_MONTH = r.BILLINGS_MONTH;