---------------------------------------------------------------------
-- Operating Income Actuals Dynamic Table
-- Revenue - Total Cogs - Opex = Operating Income
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_OPERATING_INCOME_ACTUALS
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH MONTHS AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS BILLING_MONTH
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE FISCAL_YEAR = (
        SELECT FISCAL_YEAR
        FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
        WHERE CALENDAR_DATE = CURRENT_DATE
    )
)
SELECT
    m.BILLING_MONTH,
    COALESCE(r.REVENUE, 0) - COALESCE(c.TOTAL_COGS, 0) - COALESCE(o.TOTAL_OPEX, 0) AS TOTAL_OPERATING_INCOME
FROM MONTHS m
LEFT JOIN FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_REVENUE_ACTUALS r
    ON m.BILLING_MONTH = r."Fiscal Month"
LEFT JOIN (
    SELECT BILLING_MONTH, SUM(EXPENDITURE_AMOUNT) AS TOTAL_COGS
    FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_COGS_ACTUALS
    GROUP BY BILLING_MONTH
) c ON m.BILLING_MONTH = c.BILLING_MONTH
LEFT JOIN (
    SELECT BILLING_MONTH, TOTAL_AMOUNT AS TOTAL_OPEX
    FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_OPEX_ACTUALS
) o ON m.BILLING_MONTH = o.BILLING_MONTH
ORDER BY m.BILLING_MONTH;
