USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA ARCHITECTURAL_COMPONENT;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;



-- Create Fiscal Calendar Events --
CREATE OR REPLACE TABLE FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.FISCAL_CALENDAR_EVENTS (
    DATE_KEY            NUMBER(10)    NOT NULL  COMMENT 'Foreign key to DIMENSION_FISCAL_CALENDAR (YYYYMMDD format)',
    EVENT_TYPE          VARCHAR(50)   NOT NULL  COMMENT 'Type of event (FREEZE_DATE, PAY_DAY, CORPORATE_ROLLUP)',
    DESCRIPTION         VARCHAR(255)            COMMENT 'Human-readable description of the event',

    CONSTRAINT FK_FISCAL_CALENDAR_EVENTS_DATE FOREIGN KEY (DATE_KEY)
        REFERENCES FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR (DATE_KEY)
)
COMMENT = 'Tracks key fiscal calendar events such as freeze dates, pay days, and corporate rollups';
