---------------------------------------------------------------------
-- Operating Income Actuals Dynamic Table
-- Revenue - Total Cogs - Opex = Operating Income
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_OPERATING_INCOME_ACTUALS
    TARGET_LAG = DOWNSTREAM
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    r."Fiscal Month" AS BILLING_MONTH,
    r.REVENUE - COALESCE(c.TOTAL_COGS, 0) - COALESCE(o.TOTAL_OPEX, 0) AS TOTAL_OPERATING_INCOME
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_REVENUE_ACTUALS r
LEFT JOIN (
    SELECT BILLING_MONTH, SUM(EXPENDITURE_AMOUNT) AS TOTAL_COGS
    FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_TOTAL_COGS_ACTUALS
    GROUP BY BILLING_MONTH
) c ON r."Fiscal Month" = c.BILLING_MONTH
LEFT JOIN (
    SELECT
        LEFT(BILLING_MONTH, 4) || '-M' || RIGHT(BILLING_MONTH, 2) AS BILLING_MONTH,
        TOTAL_AMOUNT AS TOTAL_OPEX
    FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_OPEX_ACTUALS
) o ON r."Fiscal Month" = o.BILLING_MONTH
ORDER BY BILLING_MONTH;
