-- SCHEMA MANAGEMENT --


-- Setup --
USE ROLE FIELD_SYSTEMS_ADMIN_ROLE;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Create Schema --
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.BUSINESS_DATA;
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.USER_INPUT;
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT;
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK;



-- Manage Schema --
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;



GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.BUSINESS_DATA TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.USER_INPUT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;



GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
