-- Dynamic table for OCOGS carveouts and consolidated carveout view pivoted by billing month
-- Co-authored with CoCo
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_BILLING_MONTH(
    RECEIVER_CODE,
    BILLING_MONTH
) TARGET_LAG = '1 minute' REFRESH_MODE = FULL INITIALIZE = ON_CREATE WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH current_fiscal_year AS (
    SELECT DISTINCT FISCAL_YEAR
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),
months AS (
    SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS MONTH_NUM
    FROM TABLE(GENERATOR(ROWCOUNT => 12))
)
SELECT
    r.RECEIVER_CODE,
    fy.FISCAL_YEAR || '-' || LPAD(m.MONTH_NUM::VARCHAR, 2, '0') AS BILLING_MONTH
FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVERS_LIST r
CROSS JOIN current_fiscal_year fy
CROSS JOIN months m