USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

-- DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST (UNIT_PRICE * UNITS_SOLD = BILLING_TOTAL)
CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_BOTTOMS_UP_BILLINGS_FORECAST
(
    RECEIVER_CODE,
    BILLING_MONTH,
    BILLING_TOTAL
)
LAG = DOWNSTREAM
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    COALESCE(p.RECEIVER_CODE, s.RECEIVER_CODE) AS RECEIVER_CODE,
    COALESCE(p.BILLING_MONTH, s.BILLING_MONTH) AS BILLING_MONTH,
    TRY_CAST(p.UNIT_PRICE AS NUMBER(10,2)) * TRY_CAST(s.UNITS_SOLD AS NUMBER(10,2)) AS BILLING_TOTAL
FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVER_UNIT_PRICE p
INNER JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVER_UNIT_SALES s
    ON p.RECEIVER_CODE = s.RECEIVER_CODE
    AND p.BILLING_MONTH = s.BILLING_MONTH;