USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_BOTTOMS_UP_BILLINGS_ACTUALS AS

SELECT
    "Fiscal Month" AS BILLINGS_MONTH,
    "Grouping" AS RECEIVER_CODE,
    SUM("Extended Amount USD") AS ACTUAL_BILLING
FROM FIELD_SYSTEMS_EDW.BUSINESS_DATA.AG_BILLINGS_PRICE_LIST_WITH_GROUPINGS_MODEL
GROUP BY "Fiscal Month", "Grouping";
