USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVER_UNIT_PRICE
(
    RECEIVER_CODE,
    BILLING_MONTH,
    UNIT_PRICE
)
LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH latest_per_receiver AS (
    SELECT
        "GCPM-XSVDL" AS RECEIVER_CODE,
        "5CUWOFAFS4" AS M01,
        "YNFIZFT49K" AS M02,
        "UKQ9KII9QU" AS M03,
        "56A5ASYPJK" AS M04,
        "WVGWC6MNDF" AS M05,
        "-JHBQBK8AV" AS M06,
        "5GECSDR7A8" AS M07,
        "1WE8S3K8AS" AS M08,
        "KMX80TKCO1" AS M09,
        "SZSC1QSA4A" AS M10,
        "W_2GFTC9U6" AS M11,
        "DY7_LBLGV4" AS M12
    FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_20d4b72e_23f0_4ca0_a0dc_adba488f0afe"
    WHERE "GCPM-XSVDL" IS NOT NULL
      AND TOMBSTONE_VERSION IS NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY "GCPM-XSVDL"
        ORDER BY UPDATED_AT DESC
    ) = 1
),
current_fiscal_year AS (
    SELECT DISTINCT FISCAL_YEAR
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),
unpivoted AS (
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-01' AS BILLING_MONTH, M01 AS UNIT_PRICE FROM latest_per_receiver, current_fiscal_year fy WHERE M01 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-02', M02 FROM latest_per_receiver, current_fiscal_year fy WHERE M02 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-03', M03 FROM latest_per_receiver, current_fiscal_year fy WHERE M03 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-04', M04 FROM latest_per_receiver, current_fiscal_year fy WHERE M04 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-05', M05 FROM latest_per_receiver, current_fiscal_year fy WHERE M05 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-06', M06 FROM latest_per_receiver, current_fiscal_year fy WHERE M06 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-07', M07 FROM latest_per_receiver, current_fiscal_year fy WHERE M07 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-08', M08 FROM latest_per_receiver, current_fiscal_year fy WHERE M08 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-09', M09 FROM latest_per_receiver, current_fiscal_year fy WHERE M09 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-10', M10 FROM latest_per_receiver, current_fiscal_year fy WHERE M10 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-11', M11 FROM latest_per_receiver, current_fiscal_year fy WHERE M11 IS NOT NULL
    UNION ALL
    SELECT RECEIVER_CODE, fy.FISCAL_YEAR || '-12', M12 FROM latest_per_receiver, current_fiscal_year fy WHERE M12 IS NOT NULL
)
SELECT
    COALESCE(u.RECEIVER_CODE, d.RECEIVER_CODE) AS RECEIVER_CODE,
    u.BILLING_MONTH,
    u.UNIT_PRICE
FROM unpivoted u
FULL JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVERS_LIST d
    ON u.RECEIVER_CODE = d.RECEIVER_CODE;

