USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVERS_LIST
(
    RECEIVER_CODE
)
LAG = '1 minute'
REFRESH_MODE = 'FULL'
INITIALIZE = 'ON_CREATE'
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT DISTINCT "MP8XAYVAWI" AS RECEIVER_CODE
FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_50f8c004_1da0_4186_b452_ce018ecdf8b4"
WHERE "MP8XAYVAWI" IS NOT NULL
  AND TOMBSTONE_VERSION IS NULL