-- DOMO_INTEGRATION_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Create new warehouse matching DOMO configuration --
CREATE WAREHOUSE IF NOT EXISTS FIELD_SYSTEMS_DOMO_WAREHOUSE
    WAREHOUSE_SIZE = 'SMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    ENABLE_QUERY_ACCELERATION = TRUE
    QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE FIELD_SYSTEMS_DOMO_WAREHOUSE;


-- Role creation --
CREATE ROLE IF NOT EXISTS DOMO_INTEGRATION_ROLE;


--  Domo Service user --
CREATE USER IF NOT EXISTS DOMO_SERVICE_USER
    PASSWORD = 'domo_developer'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_ROLE = DOMO_INTEGRATION_ROLE
    COMMENT = 'Service account for Domo integration';


-- Update the RSA Public Key --
ALTER USER DOMO_SERVICE_USER 
SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAygHwTXh0X2ODt5BekAvoTnB3iho7ywm0BXXZa/btLD7EGkJt+ww4+wefVoEUNV78vj+jgegaxl6u0TZVkocYiUqe4u0Tkb2mpOIGkHluQPi+V/bU6NAxydVqw80g15Wu5flxtpJoBO/mFyZTfqJTt3ew0QcvdyRt3bMOJ+YIMQ3SFkUUGO+6/vMVbbJeulKoOaMqlYZaFk6qrn5yd6SZwvjfCM1gjjkGd5SZ4FynECPZBBClMuG5bgF9CDep7Id1UaX89YP9nM9eK/QGRUxSlC0idgW2wGr4vaDoDNBa/tBy+OV81yzTe7Vj6VbTtTJeQfy865PuWoC+uI2nqXKoOwIDAQAB';

DESCRIBE USER DOMO_SERVICE_USER;

SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME() AS ACCOUNT_IDENTIFIER;
SELECT CURRENT_ACCOUNT() || '.' || CURRENT_REGION() AS ACCOUNT_LOCATOR;


-- Access Control --
GRANT USAGE ON DATABASE FIELD_SYSTEMS_EDW TO ROLE DOMO_INTEGRATION_ROLE;
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;

GRANT OWNERSHIP ON WAREHOUSE FIELD_SYSTEMS_DOMO_WAREHOUSE TO ROLE DOMO_INTEGRATION_ROLE REVOKE CURRENT GRANTS;

GRANT CREATE FILE FORMAT ON SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;
GRANT CREATE STAGE ON SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;
GRANT CREATE TABLE ON SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;
GRANT USAGE ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;

GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;


-- Create Domo Connector --
CREATE OR REPLACE FILE FORMAT FIELD_SYSTEMS_EDW.RAW_DATA.DOMOCONNECTORCSVFORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE;


GRANT OWNERSHIP ON FILE FORMAT FIELD_SYSTEMS_EDW.RAW_DATA.DOMOCONNECTORCSVFORMAT TO ROLE DOMO_INTEGRATION_ROLE REVOKE CURRENT GRANTS;

GRANT ROLE DOMO_INTEGRATION_ROLE TO ROLE ACCOUNTADMIN;


-- Audit: show any grants beyond what this script defines
SHOW GRANTS TO ROLE DOMO_INTEGRATION_ROLE;