-- FIELD_SYSTEMS_ADMIN_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Role creation --
CREATE ROLE IF NOT EXISTS FIELD_SYSTEMS_ADMIN_ROLE;


-- Grant OWNERSHIP to FIELD_SYSTEMS_ADMIN_ROLE --
GRANT OWNERSHIP ON WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE TO ROLE FIELD_SYSTEMS_ADMIN_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE SCHEMAS IN DATABASE FIELD_SYSTEMS_EDW FROM ROLE FIELD_SYSTEMS_ADMIN_ROLE;
GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;


GRANT ROLE FIELD_SYSTEMS_ADMIN_ROLE TO ROLE ACCOUNTADMIN;

-- Audit: show any grants beyond what this script defines
SHOW GRANTS TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
