---------------------------------------------------------------------
-- Consolidated Carveouts View
-- Rows: Carveout type (Intech, OCOGS, DCOGS)
-- Columns: Billing months pivoted
---------------------------------------------------------------------
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.GENERAL.DYNAMIC_AG_OCOGS_PX
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT *
FROM (
    SELECT
        'Intech Carveouts' AS CARVEOUT_TYPE,
        BILLING_MONTH,
        SUM(CARVEOUT_AMOUNT) AS CARVEOUT_AMOUNT
    FROM DYNAMIC_AG_INTECH_CARVEOUTS
    GROUP BY BILLING_MONTH

    UNION ALL

    SELECT
        'OCOGS Carveouts' AS CARVEOUT_TYPE,
        BILLINGS_MONTH AS BILLING_MONTH,
        SUM(OCOGS_CARVEOUTS) AS CARVEOUT_AMOUNT
    FROM DYNAMIC_AG_OCOGS_CARVEOUTS
    GROUP BY BILLINGS_MONTH

    UNION ALL

    SELECT
        'DCOGS Carveouts' AS CARVEOUT_TYPE,
        BILLING_MONTH,
        SUM(AMOUNT) AS CARVEOUT_AMOUNT
    FROM DYNAMIC_AGIS_DCOGS
    GROUP BY BILLING_MONTH
) AS combined
PIVOT(SUM(CARVEOUT_AMOUNT) FOR BILLING_MONTH IN (
    '2026-07', '2026-08', '2026-09', '2026-10', '2026-11', '2026-12'
))
AS p (CARVEOUT_TYPE, "2026-07", "2026-08", "2026-09", "2026-10", "2026-11", "2026-12");