-- Use fiscal calendar to standardize fiscal period and calculate carveout
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA COMPUTATIONAL_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;



CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_OTHER_REVENUE_ACTUALS
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH CURRENT_FISCAL AS (
    SELECT FISCAL_YEAR, FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE
)
SELECT
    REPLACE(fc.FISCAL_MONTH_CODE, '-M', '-') AS FISCAL_MONTH,
    COALESCE(SUM(b.TOTAL_BILLINGS), 0) - ABS(COALESCE(SUM(r.REVENUE), 0)) AS TOTAL_CARVEOUT
FROM (
    SELECT DISTINCT FISCAL_YEAR, FISCAL_MONTH, FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
) fc
CROSS JOIN CURRENT_FISCAL cf
LEFT JOIN FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_REVENUE_ACTUALS r
    ON r."Fiscal Month" = REPLACE(fc.FISCAL_MONTH_CODE, '-M', '-')
LEFT JOIN (
    SELECT
        BILLINGS_MONTH,
        SUM(ACTUAL_BILLING) AS TOTAL_BILLINGS
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.VIEW_AG_BOTTOMS_UP_BILLINGS_ACTUALS
    GROUP BY BILLINGS_MONTH
) b
    ON b.BILLINGS_MONTH = REPLACE(fc.FISCAL_MONTH_CODE, '-M', '-')
WHERE r."Fiscal Month" IS NOT NULL
  AND fc.FISCAL_YEAR = cf.FISCAL_YEAR
  AND fc.FISCAL_MONTH_CODE != cf.FISCAL_MONTH_CODE
GROUP BY fc.FISCAL_MONTH_CODE
ORDER BY fc.FISCAL_MONTH_CODE ASC;


-- SELECT * FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_OTHER_REVENUE_ACTUALS;