-- Ag Bottoms Up Revenue Forecast --


-- Setup --
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA GENERAL;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Create dynamic table for Bottoms Up Revenue Calculation
CREATE OR REPLACE DYNAMIC TABLE DYNAMIC_AG_BOTTOMS_UP_REVENUE_FORECAST
    TARGET_LAG = '24 hours'
    WAREHOUSE = 'FIELD_SYSTEMS_GENERAL_WAREHOUSE'
    AS
    SELECT DYNAMIC_AG_UNIT_PRICE_TABLE.RECEIVER_CODE
           , SUM("Unit Selling Price USD" * "UNITS_SOLD") AS RECEIVER_REVENUE
           , DEV_AG_UNIT_SALES.BILLINGS_MONTH
    FROM DYNAMIC_AG_UNIT_PRICE_TABLE
    JOIN DEV_AG_UNIT_SALES
    ON DYNAMIC_AG_UNIT_PRICE_TABLE.RECEIVER_CODE = DEV_AG_UNIT_SALES.RECEIVER_CODE
    GROUP BY DYNAMIC_AG_UNIT_PRICE_TABLE.RECEIVER_CODE
             , DEV_AG_UNIT_SALES.BILLINGS_MONTH;


-- select * from DYNAMIC_AG_BOTTOMS_UP_REVENUE;
