USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA DISPLAY_AGIS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.DISPLAY_AGIS.VIEW_AG_OPEX_CONSOLIDATED AS

WITH current_period AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),

actuals AS (
    SELECT
        BILLING_MONTH,
        TOTAL_AMOUNT,
        'ACTUAL' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_OPEX_ACTUALS
    CROSS JOIN current_period cp
    WHERE BILLING_MONTH < cp.FISCAL_MONTH_CODE
),

forecast AS (
    SELECT
        BILLING_MONTH,
        TOTAL_AMOUNT,
        'FORECAST' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_OPEX_FORECAST
    CROSS JOIN current_period cp
    WHERE BILLING_MONTH >= cp.FISCAL_MONTH_CODE
)

SELECT BILLING_MONTH, TOTAL_AMOUNT, SOURCE
FROM actuals

UNION ALL

SELECT BILLING_MONTH, TOTAL_AMOUNT, SOURCE
FROM forecast

ORDER BY BILLING_MONTH;
