---------------------------------------------------------------------
-- Bottoms Up COGS + OPEX Forecast Dynamic Table
-- Combines EXPENDITURE_AMOUNT from Total COGS and OPEX_AMOUNT from OPEX Manual Forecast
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_OPEX_FORECAST
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
WITH MONTHS AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS BILLING_MONTH
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE FISCAL_YEAR = (
        SELECT FISCAL_YEAR
        FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
        WHERE CALENDAR_DATE = CURRENT_DATE
    )
),
FORECAST AS (
    SELECT
        BILLING_MONTH,
        SUM(COALESCE(OPEX_AMOUNT, 0)) AS TOTAL_AMOUNT
    FROM FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_OPEX_MANUAL_FORECAST
    GROUP BY BILLING_MONTH
)
SELECT
    m.BILLING_MONTH,
    COALESCE(f.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT
FROM MONTHS m
LEFT JOIN FORECAST f ON m.BILLING_MONTH = f.BILLING_MONTH
ORDER BY m.BILLING_MONTH;

SELECT * FROM FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_OPEX_FORECAST;