---------------------------------------------------------------------
-- Opex Actuals Dynamic Table
-- Aggregates OPEX actuals from computational component
---------------------------------------------------------------------
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA WORKFLOW_COMPONENT;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.WORKFLOW_COMPONENT.DYNAMIC_AG_OPEX_ACTUALS
    TARGET_LAG = '1 minute'
    REFRESH_MODE = FULL
    WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    BILLING_MONTH,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.AG_OPEX_ACTUALS
GROUP BY BILLING_MONTH
ORDER BY BILLING_MONTH;
