USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA DISPLAY_AGIS;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


CREATE OR REPLACE VIEW FIELD_SYSTEMS_EDW.DISPLAY_AGIS.VIEW_AG_INTECH_FORECAST_STANDALONE AS

WITH current_period AS (
    SELECT DISTINCT
        REPLACE(FISCAL_MONTH_CODE, '-M', '-') AS FISCAL_MONTH_CODE
    FROM FIELD_SYSTEMS_EDW.ARCHITECTURAL_COMPONENT.DIMENSION_FISCAL_CALENDAR
    WHERE CALENDAR_DATE = CURRENT_DATE()
),

forecast AS (
    SELECT
        UPPER(RECEIVER_CODE) AS RECEIVER_CODE,
        BILLING_MONTH,
        SUM(CARVEOUT_AMOUNT) AS CARVEOUT_AMOUNT,
        'FORECAST' AS SOURCE
    FROM FIELD_SYSTEMS_EDW.COMPUTATIONAL_COMPONENT.DYNAMIC_AG_INTECH_FORECAST
    CROSS JOIN current_period cp
    WHERE BILLING_MONTH >= cp.FISCAL_MONTH_CODE
    GROUP BY UPPER(RECEIVER_CODE), BILLING_MONTH
)

SELECT f.RECEIVER_CODE, f.BILLING_MONTH, f.CARVEOUT_AMOUNT, f.SOURCE
FROM forecast f
LEFT JOIN FIELD_SYSTEMS_EDW.USER_INPUT.DYNAMIC_AG_RECEIVERS_LIST r
    ON UPPER(f.RECEIVER_CODE) = UPPER(r.RECEIVER_CODE)
ORDER BY r.SORT_ORDER, f.BILLING_MONTH;
