-- Dynamic tables: CONFIGURATION_AG_INTECH and DYNAMIC_AG_INTECH_FORECAST
-- Co-authored with CoCo
USE ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
USE DATABASE FIELD_SYSTEMS_EDW;
USE SCHEMA USER_INPUT;
USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;

CREATE OR REPLACE DYNAMIC TABLE FIELD_SYSTEMS_EDW.USER_INPUT.CONFIGURATION_AG_INTECH
(
    RECEIVER_CODE,
    BILLING_MONTH,
    CARVEOUTS_PERCENTAGE,
    RATE_PER_UNIT,
    OTHER_BA,
    NATURAL_ACCOUNT  
)
TARGET_LAG = '1 minute'
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = FIELD_SYSTEMS_GENERAL_WAREHOUSE
AS
SELECT
    "-TXCKXB7OL" AS RECEIVER_CODE,
    SPLIT_PART("AOJUL9XHAW", '-', 1) || '-' || LPAD(SPLIT_PART("AOJUL9XHAW", '-', 2), 2, '0') AS BILLING_MONTH,
    "TBS5_YF9K6" AS CARVEOUTS_PERCENTAGE,
    "YZZYL9W93N" AS RATE_PER_UNIT,
    "F_MAHRXFEG" AS OTHER_BA,
    "E0DAAH04G7" AS NATURAL_ACCOUNT
FROM FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK."SIGDS_c11b36b0_fff5_4c2b_8e96_a68300a068c7"
WHERE "-TXCKXB7OL" IS NOT NULL
  AND TOMBSTONE_VERSION IS NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY "-TXCKXB7OL", "AOJUL9XHAW"
    ORDER BY UPDATED_AT DESC
) = 1;