-- DOMO_INTEGRATION_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Role creation --
CREATE ROLE IF NOT EXISTS DOMO_INTEGRATION_ROLE;


-- Access Control --
GRANT USAGE ON DATABASE FIELD_SYSTEMS_EDW TO ROLE DOMO_INTEGRATION_ROLE;
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE DOMO_INTEGRATION_ROLE;

GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.RAW_DATA TO ROLE DOMO_INTEGRATION_ROLE;


GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE DOMO_INTEGRATION_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE DOMO_INTEGRATION_ROLE;

GRANT USAGE ON WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE TO ROLE DOMO_INTEGRATION_ROLE;


--  Domo Service user --
CREATE USER IF NOT EXISTS DOMO_SERVICE_USER
    PASSWORD = 'domo_developer'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_ROLE = DOMO_INTEGRATION_ROLE
    COMMENT = 'Service account for Domo integration';


-- Update the RSA Public Key --
ALTER USER DOMO_SERVICE_USER 
SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAygHwTXh0X2ODt5BekAvoTnB3iho7ywm0BXXZa/btLD7EGkJt+ww4+wefVoEUNV78vj+jgegaxl6u0TZVkocYiUqe4u0Tkb2mpOIGkHluQPi+V/bU6NAxydVqw80g15Wu5flxtpJoBO/mFyZTfqJTt3ew0QcvdyRt3bMOJ+YIMQ3SFkUUGO+6/vMVbbJeulKoOaMqlYZaFk6qrn5yd6SZwvjfCM1gjjkGd5SZ4FynECPZBBClMuG5bgF9CDep7Id1UaX89YP9nM9eK/QGRUxSlC0idgW2wGr4vaDoDNBa/tBy+OV81yzTe7Vj6VbTtTJeQfy865PuWoC+uI2nqXKoOwIDAQAB';

DESCRIBE USER DOMO_SERVICE_USER;

SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME() AS ACCOUNT_IDENTIFIER;
SELECT CURRENT_ACCOUNT() || '.' || CURRENT_REGION() AS ACCOUNT_LOCATOR;


-- Create Domo Connector --
CREATE OR REPLACE FILE FORMAT FIELD_SYSTEMS_EDW.GENERAL.DOMOCONNECTORCSVFORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE;

GRANT OWNERSHIP ON FILE FORMAT FIELD_SYSTEMS_EDW.GENERAL.DOMOCONNECTORCSVFORMAT TO ROLE DOMO_INTEGRATION_ROLE COPY CURRENT GRANTS;

GRANT USAGE ON FILE FORMAT FIELD_SYSTEMS_EDW.GENERAL.DOMOCONNECTORCSVFORMAT TO ROLE DOMO_INTEGRATION_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE DOMO_INTEGRATION_ROLE;


-- Managing Ownership of individual tables --
GRANT OWNERSHIP ON TABLE FIELD_SYSTEMS_EDW.GENERAL.RAW_DATA_ONE_AG TO ROLE DOMO_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE FIELD_SYSTEMS_EDW.GENERAL.RAW_DATA_EBS_EXPENSE_DETAILS TO ROLE DOMO_INTEGRATION_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE FIELD_SYSTEMS_EDW.GENERAL.RAW_DATA_REVPRO_WATERFALL TO ROLE DOMO_INTEGRATION_ROLE REVOKE CURRENT GRANTS;

