-- Grant privileges for FIELD_SYSTEMS_DEVELOPER_ROLE including stage and file format access
-- Co-authored with CoCo


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Role creation --
CREATE ROLE IF NOT EXISTS FIELD_SYSTEMS_DEVELOPER_ROLE;


-- Access Control --
GRANT USAGE ON DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT USAGE ON WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT CREATE TABLE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT CREATE STAGE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT READ, WRITE ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;



CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.SIGMA_WRITEBACK;
GRANT USAGE, CREATE TABLE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT USAGE, CREATE VIEW ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
