-- FIELD_SYSTEMS_DEVELOPER_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Role creation --
CREATE ROLE IF NOT EXISTS FIELD_SYSTEMS_DEVELOPER_ROLE;


-- Access Control --
GRANT USAGE ON DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT USAGE ON WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE REVOKE CURRENT GRANTS;
REVOKE OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;

REVOKE OWNERSHIP ON FUTURE PIPES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL FROM ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;


-- Audit: show any grants beyond what this script defines
SHOW GRANTS TO ROLE FIELD_SYSTEMS_DEVELOPER_ROLE;
