-- FIELD_SYSTEMS_ADMIN_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Role creation --
CREATE ROLE IF NOT EXISTS FIELD_SYSTEMS_ADMIN_ROLE;


-- Grant OWNERSHIP to FIELD_SYSTEMS_ADMIN_ROLE --
GRANT OWNERSHIP ON DATABASE FIELD_SYSTEMS_EDW TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON ALL STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON ALL TASKS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;

GRANT OWNERSHIP ON WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE TO ROLE FIELD_SYSTEMS_ADMIN_ROLE;
