-- First Run --

USE ROLE ACCOUNTADMIN;


-- Create database and schema --
CREATE DATABASE IF NOT EXISTS FIELD_SYSTEMS_EDW;
CREATE SCHEMA IF NOT EXISTS FIELD_SYSTEMS_EDW.GENERAL;


-- Create new warehouse matching GENERAL configuration --
CREATE WAREHOUSE IF NOT EXISTS FIELD_SYSTEMS_GENERAL_WAREHOUSE
    WAREHOUSE_SIZE = 'SMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    ENABLE_QUERY_ACCELERATION = TRUE
    QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2
    INITIALLY_SUSPENDED = TRUE;
