-- SIGMA_INTEGRATION_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Role creation --
CREATE ROLE IF NOT EXISTS SIGMA_INTEGRATION_ROLE;


-- Access Control --
GRANT USAGE ON DATABASE FIELD_SYSTEMS_EDW TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT USAGE ON WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT UPDATE ON ALL TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA FIELD_SYSTEMS_EDW.GENERAL TO ROLE SIGMA_INTEGRATION_ROLE;

-- OAuth Credentials
CREATE SECURITY INTEGRATION IF NOT EXISTS SIGMA_INTEGRATION_OAUTH
    TYPE = OAUTH
    ENABLED = TRUE
    OAUTH_CLIENT = CUSTOM
    OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'
    OAUTH_REDIRECT_URI = 'https://aws-api.sigmacomputing.com/api/v2/oauth/1/authcode'
    OAUTH_ISSUE_REFRESH_TOKENS = TRUE
    OAUTH_REFRESH_TOKEN_VALIDITY = 86400
    OAUTH_ENFORCE_PKCE = TRUE;

GRANT USAGE ON INTEGRATION SIGMA_INTEGRATION_OAUTH TO ROLE SIGMA_INTEGRATION_ROLE;

-- SELECT SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('SIGMA_INTEGRATION_OAUTH');
