-- SIGMA_INTEGRATION_ROLE --


-- Setup --
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE FIELD_SYSTEMS_GENERAL_WAREHOUSE;


-- Create new warehouse matching SIGMA configuration --
CREATE WAREHOUSE IF NOT EXISTS FIELD_SYSTEMS_SIGMA_WAREHOUSE
    WAREHOUSE_SIZE = 'SMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    ENABLE_QUERY_ACCELERATION = TRUE
    QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE FIELD_SYSTEMS_SIGMA_WAREHOUSE;


-- OAuth Credentials
CREATE SECURITY INTEGRATION IF NOT EXISTS SIGMA_INTEGRATION_OAUTH
    TYPE = OAUTH
    ENABLED = TRUE
    OAUTH_CLIENT = CUSTOM
    OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'
    OAUTH_REDIRECT_URI = 'https://aws-api.sigmacomputing.com/api/v2/oauth/1/authcode'
    OAUTH_ISSUE_REFRESH_TOKENS = TRUE
    OAUTH_REFRESH_TOKEN_VALIDITY = 86400
    OAUTH_ENFORCE_PKCE = TRUE;

-- SELECT SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('SIGMA_INTEGRATION_OAUTH');


-- Role creation --
CREATE ROLE IF NOT EXISTS SIGMA_INTEGRATION_ROLE;


-- Access management --
GRANT USAGE ON DATABASE FIELD_SYSTEMS_EDW TO ROLE SIGMA_INTEGRATION_ROLE;
GRANT USAGE ON INTEGRATION SIGMA_INTEGRATION_OAUTH TO ROLE SIGMA_INTEGRATION_ROLE;

GRANT OWNERSHIP ON WAREHOUSE FIELD_SYSTEMS_SIGMA_WAREHOUSE TO ROLE SIGMA_INTEGRATION_ROLE REVOKE CURRENT GRANTS;


-- Audit: show any grants beyond what this script defines
SHOW GRANTS TO ROLE SIGMA_INTEGRATION_ROLE;
